import random
import collections

class MedicalLLM:
    def generate(self, prompt: str) -> str:
        """
        Simulates an LLM generating a response. Adds some randomness to responses.
        """
        if "cultural context" in prompt.lower():
            return f"Culturally adapted response to: {prompt[:50]}... (LLM simulated)\nFurther details adjusted for cultural nuances and health beliefs. Random factor: {random.randint(1, 10)}"
        elif "balanced demonstrations" in prompt.lower():
            return f"Response based on balanced examples for: {prompt[:50]}... (LLM simulated)\nEnsuring fair representation in medical guidance. Random factor: {random.randint(1, 10)}"
        elif "attributes to vary" in prompt.lower():
            return f"Synthetic data generated by varying attributes: {prompt[:50]}... (LLM simulated)\nCreated diverse patient profiles. Random factor: {random.randint(1, 10)}"
        elif "for and against" in prompt.lower():
            return f"Debate-style assessment of claim: {prompt[:50]}... (LLM simulated)\nArguments presented for and against for comprehensive view. Random factor: {random.randint(1, 10)}"
        else:
            return f"Standard LLM response to: {prompt[:50]}... (LLM simulated)\nProviding general medical information. Random factor: {random.randint(1, 10)}"

class PromptEngineer:
    def _create_base_prompt(self, query: str, context: str = "", examples: list = None) -> str:
        base = f"Given the following query: {query}"
        if context:
            base += f"\nContext: {context}"
        if examples:
            base += "\nExamples:\n" + "\n".join([f"- {ex}" for ex in examples])
        return base

    def create_dense_prompts(self, query: str, exemplar_sets: list[list[str]], cultural_context: dict = None) -> list[str]:
        prompts = []
        cultural_instruction = self._format_cultural_context(cultural_context) if cultural_context else ""
        for i, examples in enumerate(exemplar_sets):
            prompt = self._create_base_prompt(query, examples=examples) + f"\n{cultural_instruction}\nPlease provide a comprehensive medical explanation (Prompt Set {i+1})."
            prompts.append(prompt)
        return prompts

    def create_balanced_demonstration_prompt(self, query: str, balanced_examples: list[str], cultural_context: dict = None) -> str:
        cultural_instruction = self._format_cultural_context(cultural_context) if cultural_context else ""
        prompt = self._create_base_prompt(query, examples=balanced_examples) + f"\n{cultural_instruction}\nEnsure the medical information is fair and balanced across diverse demographics."
        return prompt

    def create_cultural_awareness_prompt(self, query: str, cultural_context: dict, examples: list = None) -> str:
        cultural_instruction = self._format_cultural_context(cultural_context)
        prompt = self._create_base_prompt(query, examples=examples) + f"\n{cultural_instruction}\nProvide medical information tailored to this cultural background."
        return prompt

    def create_attrprompt_data_generation_prompt(self, base_scenario: str, attributes_to_vary: dict) -> str:
        attrs_str = ", ".join([f"{k} (e.g., {', '.join(v)})" for k, v in attributes_to_vary.items()])
        prompt = f"Generate 5 distinct medical patient scenarios based on the following base: '{base_scenario}'.\nVary the following attributes in each scenario: {attrs_str}. Ensure diversity."
        return prompt

    def create_debate_style_prompt(self, claim: str, context: str = "") -> str:
        prompt = f"Given the claim: '{claim}'"
        if context:
            prompt += f"\nContext: {context}"
        prompt += "\nProvide arguments for and against this claim, citing potential evidence."
        return prompt
    
    def _format_cultural_context(self, cultural_context: dict) -> str:
        if not cultural_context:
            return ""
        formatted_context = f"Consider the following cultural context: Language='{cultural_context.get('language', 'English')}'"
        if 'idioms' in cultural_context:
            formatted_context += f", Idioms='{', '.join(cultural_context['idioms'])}'"
        if 'medical_beliefs' in cultural_context: 
            formatted_context += f", Medical Beliefs='{cultural_context['medical_beliefs']}'"
        if 'sensitivities' in cultural_context:
            formatted_context += f", Sensitivities='{cultural_context['sensitivities']}'"
        return formatted_context

class BiasMitigation:
    def _aggregate_dense_responses(self, responses: list[str]) -> str:
        if not responses:
            return ""
        # Simple aggregation: take the first response or concatenate for demonstration
        # In a real system, this would involve more sophisticated summarization or consensus algorithms
        return "Aggregated response based on multiple perspectives:\n" + "\n---\n".join(responses)

    def _perform_bias_check(self, text: str) -> list[str]:
        detected_biases = []
        if "general medical information" in text.lower() and random.random() < 0.3:
            detected_biases.append("Potential for lack of cultural specificity")
        if "fair representation" not in text.lower() and random.random() < 0.2:
            detected_biases.append("Possible demographic imbalance in examples")
        if "gender specific" in text.lower() and random.random() < 0.1:
            detected_biases.append("Gender bias detected")
        return detected_biases

    def _mitigate_bias(self, text: str, detected_biases: list[str]) -> str:
        if not detected_biases:
            return text
        
        mitigated_text = text + "\n\n(Bias Mitigation Applied: "
        for bias in detected_biases:
            if "cultural specificity" in bias:
                mitigated_text += "Rephrased to be more culturally neutral/inclusive. "
            elif "demographic imbalance" in bias:
                mitigated_text += "Added considerations for diverse demographics. "
            elif "gender bias" in bias:
                mitigated_text += "Rephrased to use gender-neutral language. "
        mitigated_text += ")"
        return mitigated_text

class MedicalInformationSystem:
    def __init__(self):
        self.medical_llm = MedicalLLM()
        self.prompt_engineer = PromptEngineer()
        self.bias_mitigation = BiasMitigation()

    def get_medical_information(self, query: str, demographic_info: dict, cultural_context: dict) -> dict:
        # Simulate exemplar sets for DENSE and Balanced Demonstrations
        exemplar_set_1 = [f"Patient A ({demographic_info.get('age', '30')}y, {demographic_info.get('gender', 'M')}): Had headache, given ibuprofen."]
        exemplar_set_2 = [f"Patient B (45y, F): Had migraine, prescribed sumatriptan."]
        exemplar_set_3 = [f"Patient C (20y, {demographic_info.get('gender', 'F')}, {demographic_info.get('ethnicity', 'Asian')}): Had fever, advised rest and fluids."]
        exemplar_sets = [exemplar_set_1, exemplar_set_2, exemplar_set_3]

        # For balanced demonstrations, we might create a more diverse set based on demographic_info
        balanced_examples = [
            f"Example for {demographic_info.get('ethnicity', 'Hispanic')} male, 60 with diabetes: Recommended diet changes.",
            f"Example for {demographic_info.get('ethnicity', 'African')} female, 25 with asthma: Advised inhaler usage.",
            f"Example for {demographic_info.get('ethnicity', 'Caucasian')} child, 8 with cold: Suggested over-the-counter meds."
        ]

        # 1. Prepare Prompts (DENSE, Cultural Awareness, Balanced Demonstrations)
        dense_prompts = self.prompt_engineer.create_dense_prompts(query, exemplar_sets, cultural_context)
        balanced_prompt = self.prompt_engineer.create_balanced_demonstration_prompt(query, balanced_examples, cultural_context)
        cultural_prompt = self.prompt_engineer.create_cultural_awareness_prompt(query, cultural_context)

        all_prompts = dense_prompts + [balanced_prompt, cultural_prompt]

        # 2. LLM Interaction
        llm_responses = [self.medical_llm.generate(p) for p in all_prompts]

        # 3. Aggregation
        aggregated_response = self.bias_mitigation._aggregate_dense_responses(llm_responses)

        # 4. Bias Check & Mitigation
        detected_biases = self.bias_mitigation._perform_bias_check(aggregated_response)
        final_medical_info = self.bias_mitigation._mitigate_bias(aggregated_response, detected_biases)

        return {"medical_information": final_medical_info, "detected_biases": detected_biases}

    def generate_diverse_medical_data(self, base_scenario: str, attributes_to_vary: dict, num_samples: int) -> list[str]:
        data_generation_prompt = self.prompt_engineer.create_attrprompt_data_generation_prompt(base_scenario, attributes_to_vary)
        generated_data = []
        for _ in range(num_samples):
            # Simulate generating varied data points based on the prompt
            response = self.medical_llm.generate(data_generation_prompt)
            generated_data.append(f"Simulated Data Point: {response}")
        return generated_data

    def get_balanced_claim_assessment(self, claim: str, context: str = "") -> dict:
        debate_prompt = self.prompt_engineer.create_debate_style_prompt(claim, context)
        llm_assessment = self.medical_llm.generate(debate_prompt)
        
        # Simulate parsing arguments for and against
        arguments_for = f"Argument For: {llm_assessment[:int(len(llm_assessment)*0.6)]} (simulated)"
        arguments_against = f"Argument Against: {llm_assessment[int(len(llm_assessment)*0.6):]} (simulated)"

        return {
            "claim": claim,
            "assessment_llm_raw": llm_assessment,
            "arguments_for": arguments_for,
            "arguments_against": arguments_against
        }

# Example Usage:
if __name__ == "__main__":
    system = MedicalInformationSystem()

    print("\n--- Getting Medical Information (Culturally-Aware and Bias-Mitigated) ---")
    demographic_info = {"age": "40", "gender": "F", "ethnicity": "South Asian", "pre_existing_conditions": "Hypertension"}
    cultural_context = {
        "language": "Hindi",
        "idioms": ["ghar ka nuskha"], 
        "medical_beliefs": "Prefers traditional remedies alongside modern medicine",
        "sensitivities": "Avoid direct confrontation about lifestyle choices"
    }
    query = "What are the best practices for managing hypertension?"
    medical_info_result = system.get_medical_information(query, demographic_info, cultural_context)
    print(f"Final Medical Information: {medical_info_result['medical_information']}")
    print(f"Detected Biases: {medical_info_result['detected_biases']}")

    print("\n--- Generating Diverse Medical Data (AttrPrompt) ---")
    base_scenario = "A 50-year-old male with mild diabetes."
    attributes_to_vary = {
        "age": ["30", "70"],
        "gender": ["female"],
        "condition_severity": ["severe", "pre-diabetic"],
        "ethnicity": ["African American", "East Asian"]
    }
    diverse_data = system.generate_diverse_medical_data(base_scenario, attributes_to_vary, num_samples=3)
    for data_point in diverse_data:
        print(data_point)

    print("\n--- Getting Balanced Claim Assessment (Debate-Style Evidence Aggregation) ---")
    medical_claim = "Is a low-carb diet effective for long-term weight loss?"
    claim_assessment = system.get_balanced_claim_assessment(medical_claim)
    print(f"Claim: {claim_assessment['claim']}")
    print(f"Arguments For: {claim_assessment['arguments_for']}")
    print(f"Arguments Against: {claim_assessment['arguments_against']}")
    print(f"Raw LLM Assessment: {claim_assessment['assessment_llm_raw']}")
