from fastapi import FastAPI, Request
import httpx
import uvicorn

app = FastAPI()

VLLM_API_URL = "http://localhost:8000/generate"

@app.post("/chat")
async def chat_endpoint(request: Request):
    data = await request.json()
    user_message = data.get("message")

    if not user_message:
        return {"response": "Please provide a message."}

    payload = {
        "prompt": user_message,
        "max_tokens": 200,
        "temperature": 0.7,
        "n": 1,
        "stop": ["\nUser:", "\nAssistant:"]
    }

    try:
        async with httpx.AsyncClient() as client:
            response = await client.post(VLLM_API_URL, json=payload, timeout=120.0)
            response.raise_for_status()
            vllm_output = response.json()

            if "choices" in vllm_output and len(vllm_output["choices"]) > 0:
                generated_text = vllm_output["choices"][0]["text"].strip()
                return {"response": generated_text}
            else:
                return {"response": "Error: No text generated by LLM."}
    except httpx.HTTPStatusError as e:
        return {"response": f"Error from vLLM server: {e.response.status_code} - {e.response.text}"}
    except httpx.RequestError as e:
        return {"response": f"Could not connect to vLLM server at {VLLM_API_URL}. Please ensure it is running: {e}"}
    except Exception as e:
        return {"response": f"An unexpected error occurred: {e}"}

if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=8001)