from pydantic import BaseModel, Field
from typing import List, Optional
from fastapi import FastAPI
import instructor

# --- Pydantic Data Models ---

class Medication(BaseModel):
    name: str = Field(..., description="Name of the medication")
    dosage: str = Field(..., description="Dosage instructions for the medication")
    frequency: str = Field(..., description="How often the medication should be taken")

class Procedure(BaseModel):
    name: str = Field(..., description="Name of the medical procedure")
    date: str = Field(..., description="Date when the procedure is scheduled (YYYY-MM-DD)")
    department: str = Field(..., description="Medical department performing the procedure")

class Appointment(BaseModel):
    type: str = Field(..., description="Type of appointment (e.g., follow-up, specialist consultation)")
    date: str = Field(..., description="Date of the appointment (YYYY-MM-DD)")
    time: str = Field(..., description="Time of the appointment (HH:MM AM/PM)")
    doctor: str = Field(..., description="Name of the doctor for the appointment")

class TreatmentPlan(BaseModel):
    patient_id: str = Field(..., description="Unique identifier for the patient")
    symptoms: List[str] = Field(..., description="List of patient's reported symptoms")
    natural_language_plan: str = Field(..., description="The original natural language treatment plan generated by the LLM")
    medications: List[Medication] = Field(..., description="List of prescribed medications")
    procedures: List[Procedure] = Field(..., description="List of recommended procedures")
    appointments: List[Appointment] = Field(..., description="List of scheduled appointments")

# --- FastAPI Application Setup ---

app = FastAPI(
    title="Medical Treatment Plan Generator and Analyzer",
    description="API to generate and structure medical treatment plans using LLMs (mocked for this example)."
)

# --- Mock OpenAI Client for Demonstration with Instructor ---
# In a real application, you would initialize openai.OpenAI() with your API key
# and instructor.patch() it. Here, we create a mock to make the example runnable
# without an actual OpenAI API key, directly returning structured data.

class MockChatCompletion:
    def create(self, model: str, messages: List[dict], response_model: BaseModel) -> BaseModel:
        # This method simulates the LLM's response being parsed into the pydantic model.
        # In a real instructor setup, the LLM would generate JSON, and instructor would validate/parse it.
        # For this mock, we directly return a hardcoded Pydantic instance.
        if response_model == TreatmentPlan:
            return TreatmentPlan(
                patient_id="PAT001",
                symptoms=["fever", "cough"],
                natural_language_plan="Patient needs rest, paracetamol 500mg three times a day for fever, and a follow-up appointment with Dr. Smith on 2024-07-23 at 10:00 AM. A chest X-ray is recommended on 2024-07-20 in Radiology.",
                medications=[
                    Medication(name="Paracetamol", dosage="500mg", frequency="TDS")
                ],
                procedures=[
                    Procedure(name="Chest X-ray", date="2024-07-20", department="Radiology")
                ],
                appointments=[
                    Appointment(type="Follow-up", date="2024-07-23", time="10:00 AM", doctor="Dr. Smith")
                ]
            )
        raise ValueError(f"Unsupported response_model in mock: {response_model.__name__}")

class MockChat:
    def __init__(self):
        self.completions = MockChatCompletion()

class MockOpenAI:
    def __init__(self):
        self.chat = MockChat()

mock_openai_client = MockOpenAI()
# Patch the mock client with instructor. This line demonstrates the intended usage,
# though for a direct mock return, its effect is conceptual here.
instructor.patch(mock_openai_client)

# --- Simulated Natural Language Plan Generation ---
# In a real application, this would be an actual LLM call based on patient input.
def generate_natural_language_plan(symptoms: List[str], history: str) -> str:
    patient_info = f"Patient presents with symptoms: {', '.join(symptoms)}. Medical history: {history or 'N/A'}."
    if "fever" in symptoms and "cough" in symptoms:
        return f"{patient_info} The patient requires rest, a prescription for an antiviral medication, and monitoring for 7 days. A follow-up appointment is recommended in one week with Dr. Smith. Consider a chest X-ray if symptoms persist."
    elif "headache" in symptoms:
        return f"{patient_info} Advise pain relievers, adequate hydration, and rest. If headache worsens, seek further medical advice. A general check-up appointment is advised with Dr. Jones."
    else:
        return f"{patient_info} General advice: rest and observe. Book a general consultation."

# --- API Request Model ---

class PatientInput(BaseModel):
    symptoms: List[str] = Field(..., description="List of patient's current symptoms (e.g., [\"fever\", \"cough\"])")
    history: Optional[str] = Field(None, description="Brief patient medical history")
    patient_id: str = Field(..., description="Unique identifier for the patient")

# --- API Endpoint ---

@app.post("/generate-treatment-plan", response_model=TreatmentPlan)
async def create_treatment_plan(patient_input: PatientInput):
    # 1. Simulate Natural Language Plan Generation
    nl_plan = generate_natural_language_plan(patient_input.symptoms, patient_input.history)

    # 2. Use instructor-patched client (mocked) to extract structured data
    # In a real scenario, the LLM would take the nl_plan and parse it into the Pydantic model.
    # Our mock directly returns a TreatmentPlan object for demonstration.
    structured_plan: TreatmentPlan = mock_openai_client.chat.completions.create(
        model="gpt-4", # Placeholder model name, not actually used by mock
        response_model=TreatmentPlan,
        messages=[
            {"role": "system", "content": "You are a medical assistant extracting structured treatment plans from natural language descriptions."},
            {"role": "user", "content": f"Extract the comprehensive treatment plan, including medications, procedures, and appointments, from the following natural language description. Assign Patient ID {patient_input.patient_id}.\n\nNatural Language Plan:\n{nl_plan}"}
        ]
    )

    # Update the structured_plan with the actual natural_language_plan and patient_id from input
    structured_plan.natural_language_plan = nl_plan
    structured_plan.patient_id = patient_input.patient_id

    return structured_plan