import sys
import io
from llm_mock import MockLLM
# portfolio_optimizer is implicitly used by the code generated by MockLLM

def run_smart_financial_advisor():
    """
    Orchestrates the Smart Financial Advisor application, demonstrating
    Program-Aided Language Model (PAL) Prompting.
    """
    print("\n--- Starting Smart Financial Advisor --- ")

    llm = MockLLM()

    # 1. Simulate user input and LLM understanding of financial goals
    user_goals = {
        "target_return": 0.10,  # User wants 10% annual return
        "risk_tolerance": "moderate", # User has a moderate risk tolerance
        "investment_horizon": "long-term", # Long-term investment horizon
        "assets_to_consider": ["Stocks", "Bonds", "Real Estate"] # Example asset classes
    }
    print(f"\nUser Input: {user_goals}")

    # 2. LLM generates Python code for portfolio optimization
    print("\nLLM is generating optimization code...")
    generated_code = llm.generate_optimization_code(user_goals)
    # print("\n--- Generated Code ---")
    # print(generated_code)
    # print("----------------------")

    # 3. Execute the generated code in a controlled environment
    print("Executing generated code for portfolio optimization...")
    optimization_results = {}
    try:
        # Capture stdout from the executed code if any (though our optimizer doesn't print)
        old_stdout = sys.stdout
        redirected_output = io.StringIO()
        sys.stdout = redirected_output

        # Define a dictionary for the `exec` environment
        # This makes `optimize_portfolio` available to the generated code
        # And captures `_optimization_results_` after execution
        exec_globals = {
            "optimize_portfolio": __import__("portfolio_optimizer").optimize_portfolio,
            "np": __import__("numpy"), # Make numpy available if the generated code needs it directly
            "_optimization_results_": None # Initialize to capture the output
        }

        exec(generated_code, exec_globals)

        # Retrieve the optimization results set by the executed code
        optimization_results = exec_globals.get("_optimization_results_", {})

        sys.stdout = old_stdout # Restore stdout
        # print(f"Executed Code Output (stdout):\n{redirected_output.getvalue()}")

        if not optimization_results:
            raise ValueError("Optimization results were not captured from the executed code.")

        print("Optimization complete. Results received by LLM.")

    except Exception as e:
        print(f"Error executing optimization code: {e}")
        optimization_results = {"error": str(e)}

    # 4. LLM synthesizes natural language investment advice
    print("\nLLM is generating investment advice...")
    investment_advice = llm.generate_advice(optimization_results, user_goals)

    # 5. Display the advice to the user
    print("\n--- Your Personalized Investment Advice ---")
    print(investment_advice)
    print("\n--- End of Smart Financial Advisor ---")

if __name__ == "__main__":
    run_smart_financial_advisor()