
import json
import io
import sys
import pandas as pd
import numpy as np

def simulate_llm_code_generation(user_prompt):
    """
    Simulates the LLM generating Python code for portfolio optimization.
    In a real PAL system, an actual LLM would generate this code based on the prompt.
    For this example, we'll return a pre-defined code snippet.
    """
    # This code would be generated by the LLM based on user_prompt
    generated_code = """
import pandas as pd
import numpy as np

def calculate_portfolio_metrics(portfolio_data):
    assets = portfolio_data['assets']
    shares = portfolio_data['shares']
    current_prices = portfolio_data['current_prices']
    expected_returns = portfolio_data['expected_returns']
    volatilities = portfolio_data['volatilities']
    correlations = portfolio_data['correlations'] # Simplified, assume independent for now

    # Convert to numpy arrays for calculation
    shares_np = np.array(shares)
    prices_np = np.array(current_prices)
    expected_returns_np = np.array(expected_returns)
    volatilities_np = np.array(volatilities)

    # Calculate current portfolio value
    current_value = np.sum(shares_np * prices_np)

    # Calculate portfolio weights
    asset_values = shares_np * prices_np
    weights = asset_values / current_value

    # Calculate portfolio expected return
    portfolio_expected_return = np.sum(weights * expected_returns_np)

    # Calculate portfolio volatility (simplified, assuming no correlations for this demo)
    # For a more accurate calculation, a covariance matrix would be needed
    portfolio_variance = np.sum((weights * volatilities_np)**2) # Assuming independence for simplicity
    portfolio_volatility = np.sqrt(portfolio_variance)

    results = {
        "current_portfolio_value": round(current_value, 2),
        "portfolio_weights": dict(zip(assets, np.round(weights, 4).tolist())),
        "portfolio_expected_return": round(portfolio_expected_return, 4),
        "portfolio_volatility": round(portfolio_volatility, 4),
    }
    return results

# Data that would be provided by the user or fetched by the LLM
# Example data based on a user prompt
# "I have 100 shares of AAPL, 50 of GOOG, 20 of TSLA.
# Current prices are AAPL: 170, GOOG: 150, TSLA: 180.
# Expected annual returns: AAPL: 0.12, GOOG: 0.10, TSLA: 0.15.
# Annual volatilities: AAPL: 0.20, GOOG: 0.18, TSLA: 0.30."
user_portfolio_data = {
    "assets": ["AAPL", "GOOG", "TSLA"],
    "shares": [100, 50, 20],
    "current_prices": [170, 150, 180],
    "expected_returns": [0.12, 0.10, 0.15],
    "volatilities": [0.20, 0.18, 0.30],
    "correlations": [] # Placeholder for future
}

# Execute the calculation
calculated_metrics = calculate_portfolio_metrics(user_portfolio_data)

# Print results in a structured format for the main program to capture
print(json.dumps(calculated_metrics))
"""
    return generated_code

def main():
    user_prompt = "Analyze my portfolio: I have 100 shares of AAPL, 50 of GOOG, 20 of TSLA. Current prices are AAPL: 170, GOOG: 150, TSLA: 180. Expected annual returns: AAPL: 0.12, GOOG: 0.10, TSLA: 0.15. Annual volatilities: AAPL: 0.20, GOOG: 0.18, TSLA: 0.30. Advise me on its performance and potential improvements."

    print(f"User Prompt: {user_prompt}\n")

    # Step 1: LLM generates code (simulated)
    print("LLM is generating Python code for portfolio analysis...")
    generated_code = simulate_llm_code_generation(user_prompt)
    print("\n--- Generated Code ---")
    print(generated_code)
    print("----------------------\n")

    # Step 2: Execute the generated code
    print("Executing generated code...")
    # Using a dictionary to capture the output of the 'exec' function
    # A more robust solution would use subprocess and capture stdout
    exec_globals = {}
    exec_locals = {}
    try:
        # Redirect stdout to capture the print statements from the executed code
        
        old_stdout = sys.stdout
        redirected_output = io.StringIO()
        sys.stdout = redirected_output

        exec(generated_code, exec_globals, exec_locals)

        sys.stdout = old_stdout # Restore stdout
        captured_output = redirected_output.getvalue()
        print("Code executed successfully. Captured output:")
        print(captured_output)

        # Assuming the generated code prints a JSON string
        results = json.loads(captured_output.strip())

        # Step 3: LLM interprets results and formulates advice
        print("\nLLM is interpreting results and formulating financial advice...")
        advice = f"Based on your portfolio analysis:\n"
        advice += f"- Current Portfolio Value: ${results['current_portfolio_value']}\n"
        advice += f"- Portfolio Expected Annual Return: {results['portfolio_expected_return'] * 100:.2f}%\n"
        advice += f"- Portfolio Annual Volatility: {results['portfolio_volatility'] * 100:.2f}%\n"
        advice += f"- Asset Weights: {json.dumps(results['portfolio_weights'])}\n\n"
        advice += "Financial Advice (generated by LLM based on calculations):\n"
        advice += "Your portfolio shows a good expected return with moderate volatility. Consider diversifying further to mitigate specific asset risks. For example, if you aim for lower volatility, you might consider allocating less to high-volatility assets like TSLA or adding some low-volatility assets. If you want higher returns and are comfortable with more risk, you could increase allocation to higher-return assets. Please consult a professional financial advisor for personalized advice."

        print(advice)

    except Exception as e:
        print(f"Error during code execution: {e}")
        # Restore stdout in case of error during exec
        sys.stdout = old_stdout

if __name__ == "__main__":
    main()
