import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import io
import base64

def analyze_company_performance(company_ticker: str, period: str = '1y'):
    """
    Simulates fetching financial data, performing analysis, and generating a report.
    In a real PAL setup, this script would be generated by an LLM based on user input.
    """

    # --- Simulate Data Fetching (replace with actual API calls like yfinance in a real app) ---
    print(f"Simulating data fetching for {company_ticker} over {period}...")
    dates = pd.date_range(end=pd.Timestamp.now(), periods=252, freq='B') # 252 business days in a year
    np.random.seed(42)
    # Generate a more realistic price series
    initial_price = 100
    returns = np.random.normal(0.0005, 0.01, len(dates))
    prices = initial_price * (1 + returns).cumprod()

    df = pd.DataFrame({
        'Date': dates,
        'Close': prices,
        'Volume': np.random.randint(1_000_000, 10_000_000, len(dates))
    }).set_index('Date')

    # --- Perform Financial Calculations ---
    print("Performing financial calculations...")
    df['Daily Return'] = df['Close'].pct_change()
    df['50-day MA'] = df['Close'].rolling(window=50).mean()
    df['200-day MA'] = df['Close'].rolling(window=200).mean()

    # Key metrics
    latest_price = df['Close'].iloc[-1]
    period_start_price = df['Close'].iloc[0]
    total_return_percentage = ((latest_price - period_start_price) / period_start_price) * 100
    avg_daily_return = df['Daily Return'].mean() * 100
    std_daily_return = df['Daily Return'].std()
    
    # Simulate industry average for comparison
    industry_avg_return = np.random.uniform(5, 20) # Random industry avg between 5-20%

    # --- Generate Visualization ---
    print("Generating visualizations...")
    fig, ax1 = plt.subplots(figsize=(12, 6))
    ax1.plot(df.index, df['Close'], label=f'{company_ticker} Close Price', color='blue')
    ax1.plot(df.index, df['50-day MA'], label='50-day Moving Average', color='orange', linestyle='--')
    ax1.plot(df.index, df['200-day MA'], label='200-day Moving Average', color='green', linestyle='--')
    ax1.set_xlabel('Date')
    ax1.set_ylabel('Price', color='blue')
    ax1.tick_params(axis='y', labelcolor='blue')
    ax1.set_title(f'{company_ticker} Stock Performance & Moving Averages ({period})')
    ax1.legend(loc='upper left')
    ax1.grid(True)

    # Save plot to an in-memory buffer and encode as base64 for easy transport
    buf = io.BytesIO()
    plt.savefig(buf, format='png', bbox_inches='tight')
    plt.close(fig) # Close the plot to free memory
    plot_base64 = base64.b64encode(buf.getvalue()).decode('utf-8')

    # --- Prepare Results for LLM ---
    report_summary = {
        "company_ticker": company_ticker,
        "period": period,
        "latest_close_price": f"${latest_price:.2f}",
        "total_period_return": f"{total_return_percentage:.2f}%",
        "average_daily_return": f"{avg_daily_return:.2f}%",
        "volatility_std_dev": f"{std_daily_return:.4f}",
        "industry_average_return": f"{industry_avg_return:.2f}%",
        "investment_outlook": "neutral" # Placeholder, LLM would interpret and refine
    }

    if total_return_percentage > industry_avg_return * 0.8: # Simple rule for positive outlook
        report_summary["investment_outlook"] = "positive"
    elif total_return_percentage < industry_avg_return * 0.5: # Simple rule for negative outlook
        report_summary["investment_outlook"] = "negative"

    return {
        "financial_metrics": report_summary,
        "plot_image_base64": plot_base64,
        "raw_data_head": df.head().to_dict()
    }

if __name__ == '__main__':
    # Example usage if run directly
    print("Running example analysis for AAPL...")
    results = analyze_company_performance("AAPL", "1y")

    print("\n--- Financial Metrics ---")
    for key, value in results['financial_metrics'].items():
        print(f"{key.replace('_', ' ').title()}: {value}")
    
    print("\n--- Raw Data Head ---")
    # For brevity, don't print full raw data
    # print(results['raw_data_head'])

    # To actually view the plot if run directly:
    # from PIL import Image
    # import io
    # img_bytes = base64.b64decode(results['plot_image_base64'])
    # img = Image.open(io.BytesIO(img_bytes))
    # img.show()
    
    print("\nAnalysis complete. A base64 encoded plot image and financial metrics have been generated.")
