import streamlit as st
import pandas as pd
import io
import json

def execute_python_code(code: str, data: pd.DataFrame) -> dict:
    exec_globals = {"pd": pd, "json": json, "DataFrame": pd.DataFrame, "Series": pd.Series}
    exec_locals = {}

    try:
        exec(code, exec_globals, exec_locals)

        if "process_data" in exec_locals and callable(exec_locals["process_data"]):
            results = exec_locals["process_data"](data)
            return {"status": "success", "output": results}
        else:
            return {"status": "error", "message": "Generated code did not define a callable 'process_data' function."}
    except Exception as e:
        return {"status": "error", "message": f"Code execution failed: {e}"}

def generate_financial_code(user_query: str, columns: list) -> str:
    code_template = f"""
import pandas as pd

def process_data(df: pd.DataFrame) -> dict:
    required_cols = ['Revenue', 'Cost_of_Goods_Sold', 'Operating_Expenses']
    for col in required_cols:
        if col not in df.columns:
            return {{'error': f'Missing required column: {{col}}'}}

    for col in required_cols:
        df[col] = pd.to_numeric(df[col], errors='coerce').fillna(0)

    total_revenue = df['Revenue'].sum()
    total_cogs = df['Cost_of_Goods_Sold'].sum()
    total_operating_expenses = df['Operating_Expenses'].sum()

    gross_profit = total_revenue - total_cogs
    net_profit = gross_profit - total_operating_expenses

    if total_revenue != 0:
        gross_profit_margin = (gross_profit / total_revenue) * 100
        net_profit_margin = (net_profit / total_revenue) * 100
    else:
        gross_profit_margin = 0
        net_profit_margin = 0

    return {{
        "Total Revenue": total_revenue,
        "Total Cost of Goods Sold": total_cogs,
        "Gross Profit": gross_profit,
        "Total Operating Expenses": total_operating_expenses,
        "Net Profit": net_profit,
        "Gross Profit Margin (%)": gross_profit_margin,
        "Net Profit Margin (%)": net_profit_margin,
        "Currency": "$",
    }}
"""
    return code_template

def generate_natural_language_report(financial_results: dict, user_query: str) -> str:
    if "error" in financial_results:
        return f"Could not generate report due to error in financial calculations: {financial_results['error']}"

    report = "### Financial Report Summary\n\n"
    report += f"Based on your request: \"{user_query}\"\n\n"
    report += "Here is a summary of the financial performance:\n\n"

    currency = financial_results.get("Currency", "")

    report += f"- **Total Revenue:** {currency}{financial_results.get('Total Revenue', 0):,.2f}\n"
    report += f"- **Total Cost of Goods Sold:** {currency}{financial_results.get('Total Cost of Goods Sold', 0):,.2f}\n"
    report += f"- **Gross Profit:** {currency}{financial_results.get('Gross Profit', 0):,.2f}\n"
    report += f"  (Gross Profit Margin: {financial_results.get('Gross Profit Margin (%)', 0):.2f}%)\n"
    report += f"- **Total Operating Expenses:** {currency}{financial_results.get('Total Operating Expenses', 0):,.2f}\n"
    report += f"- **Net Profit:** {currency}{financial_results.get('Net Profit', 0):,.2f}\n"
    report += f"  (Net Profit Margin: {financial_results.get('Net Profit Margin (%)', 0):.2f}%)\n\n"

    report += "#### Key Insights:\n"
    if financial_results.get('Net Profit', 0) > 0:
        report += "- The business achieved a positive net profit, indicating profitability.\n"
    else:
        report += "- The business incurred a net loss, suggesting areas for cost reduction or revenue enhancement.\n"

    if financial_results.get('Gross Profit Margin (%)', 0) < 20:
        report += "- The gross profit margin is relatively low, which might indicate high cost of goods sold.\n"
    elif financial_results.get('Gross Profit Margin (%)', 0) > 40:
        report += "- The gross profit margin is strong, suggesting good control over direct costs.\n"
    else:
        report += "- The gross profit margin is moderate.\n"

    report += "\n*This report is generated by an AI assistant using program-aided reasoning.*"
    return report

st.set_page_config(layout="wide", page_title="PAL Financial Analyst")

st.title("Automated Financial Report & Analysis (PAL Prompting)")
st.markdown("Upload your financial data (CSV) and ask for a report. Our AI will generate and execute Python code to ensure accurate calculations, then provide a natural language analysis.")

uploaded_file = st.file_uploader("Upload your financial data (CSV file)", type=["csv"])

if uploaded_file is not None:
    try:
        data = pd.read_csv(uploaded_file)
        st.subheader("Uploaded Data Preview:")
        st.dataframe(data.head())

        st.subheader("Ask for a Financial Report:")
        user_query = st.text_area(
            "Enter your request (e.g., 'Generate a Q3 profit and loss statement with key performance indicators and a brief analysis.')",
            "Generate a profit and loss statement with key performance indicators and a brief analysis for the provided data."
        )

        if st.button("Generate Report"):
            if not user_query:
                st.warning("Please enter a query.")
            else:
                with st.spinner("Generating and executing code, then analyzing results..."):
                    generated_code = generate_financial_code(user_query, data.columns.tolist())
                    st.expander("View Generated Python Code (Simulated)").code(generated_code, language="python")

                    execution_result = execute_python_code(generated_code, data)

                    if execution_result["status"] == "success":
                        financial_results = execution_result["output"]
                        st.success("Code executed successfully!")
                        st.subheader("Calculated Financial Metrics:")
                        st.json(financial_results)

                        final_report = generate_natural_language_report(financial_results, user_query)
                        st.subheader("Financial Analysis Report:")
                        st.markdown(final_report)
                    else:
                        st.error(f"Error during code execution: {execution_result['message']}")
                        st.info("Please check your CSV file for expected columns like 'Revenue', 'Cost_of_Goods_Sold', 'Operating_Expenses'.")

    except Exception as e:
        st.error(f"Error processing file: {e}. Please ensure it's a valid CSV.")
