import re
import io
import sys

class SmartFinancialAssistant:
    def __init__(self):
        # Template for the final LLM response
        self.llm_response_template = (
            "Based on your input, the calculations yielded:\n"
            "{calculation_result}\n\n"
            "Therefore, {final_answer_statement}"
        )

    def _parse_query_and_generate_code(self, query: str) -> tuple[str, dict]:
        """
        Simulates an LLM parsing a financial query and generating Python code.
        Returns the generated code string and a dictionary of extracted parameters.
        This is a highly simplified version for demonstration.
        """
        extracted_params = {
            "monthly_investment": 0.0,
            "years": 0,
            "annual_return_rate": 0.0
        }
        generated_code = "print('Error: Could not parse your financial query or generate relevant code.')"

        if "invest" in query.lower() and "monthly" in query.lower() and "years" in query.lower() and "annual return" in query.lower():
            monthly_investment_match = re.search(r'\$?([\d,]+\.?\d*)\s*monthly', query, re.IGNORECASE)
            years_match = re.search(r'for\s*(\d+)\s*years', query, re.IGNORECASE)
            annual_return_match = re.search(r'return of\s*(\d+\.?\d*)\%?', query, re.IGNORECASE)

            if monthly_investment_match:
                extracted_params["monthly_investment"] = float(monthly_investment_match.group(1).replace(',', ''))
            if years_match:
                extracted_params["years"] = int(years_match.group(1))
            if annual_return_match:
                extracted_params["annual_return_rate"] = float(annual_return_match.group(1))

            if all(val > 0 for val in extracted_params.values()): # Check if all required parameters were found and are positive
                code_template = f"""
# Python code generated by the Smart Financial Assistant
def calculate_future_value_and_interest(monthly_investment, years, annual_return_rate):
    monthly_rate = (annual_return_rate / 100) / 12
    num_payments = years * 12

    # Future Value of an Ordinary Annuity Formula:
    # FV = PMT * [((1 + i)^n - 1) / i]
    if monthly_rate == 0:
        # Simple sum if interest rate is zero
        future_value = monthly_investment * num_payments
    else:
        future_value = monthly_investment * (((1 + monthly_rate)**num_payments - 1) / monthly_rate)

    total_principal_invested = monthly_investment * num_payments
    total_interest_earned = future_value - total_principal_invested

    return future_value, total_interest_earned

# Parameters extracted from the user query
monthly_investment = {extracted_params["monthly_investment"]}
years = {extracted_params["years"]}
annual_return_rate = {extracted_params["annual_return_rate"]}

fv, interest = calculate_future_value_and_interest(monthly_investment, years, annual_return_rate)

print(f"Future Value: {{fv:.2f}}")
print(f"Total Interest Earned: {{interest:.2f}}")
"""
                generated_code = code_template
        return generated_code, extracted_params

    def _execute_code(self, code: str) -> str:
        """
        Executes the generated Python code in a restricted environment
        and captures its output.
        """
        output_buffer = []
        # Redirect stdout to capture print statements
        old_stdout = sys.stdout
        redirected_output = io.StringIO()
        sys.stdout = redirected_output

        try:
            # Using exec to run the generated code
            # In a real application, this would need a much more robust sandbox
            # for security and resource management (e.g., using a separate process, containerization).
            # Restrict builtins for basic security.
            exec(code, {'__builtins__': {}})
            captured_output = redirected_output.getvalue()
            output_buffer.append(captured_output)
        except Exception as e:
            output_buffer.append(f"Code execution error: {type(e).__name__}: {e}")
        finally:
            sys.stdout = old_stdout # Restore stdout

        return "".join(output_buffer)

    def process_financial_query(self, query: str) -> str:
        """
        Main function to process a financial query using PAL prompting.
        """
        print(f"User query: '{query}'")

        # Step 1: LLM (simulated) generates code and extracts parameters
        generated_code, params = self._parse_query_and_generate_code(query)
        print("\n--- Generated Python Code ---")
        print(generated_code)
        print("-----------------------------\n")

        # Step 2: Execute the generated code
        execution_output = self._execute_code(generated_code)
        print("--- Code Execution Output ---")
        print(execution_output)
        print("-----------------------------\n")

        # Step 3: LLM (simulated) uses execution output to formulate the final answer
        fv_match = re.search(r'Future Value: ([\d.,]+)', execution_output)
        interest_match = re.search(r'Total Interest Earned: ([\d.,]+)', execution_output)

        final_answer_statement = "I couldn't fully process the result due to an unexpected outcome or missing information."
        if fv_match and interest_match:
            future_value = fv_match.group(1)
            total_interest = interest_match.group(1)
            
            # Use extracted parameters for a more natural response
            monthly_inv = params["monthly_investment"]
            years_val = params["years"]
            annual_rate = params["annual_return_rate"]

            if all(val > 0 for val in [monthly_inv, years_val, annual_rate]):
                final_answer_statement = (
                    f"If you invest ${monthly_inv:.2f} monthly for {years_val} years "
                    f"with an average annual return of {annual_rate}%, "
                    f"the future value of your investment will be approximately ${future_value}, "
                    f"and you will earn approximately ${total_interest} in total interest."
                )
            else:
                final_answer_statement = (
                    f"The calculation resulted in a future value of approximately ${future_value} "
                    f"and total interest earned of approximately ${total_interest}."
                )
        elif "Error" in execution_output or "could not parse" in execution_output.lower():
             final_answer_statement = "There was an error in processing your request. Please ensure your query is clear and specific for financial calculations (e.g., specifying monthly investment amount, number of years, and annual return rate)."
        
        return self.llm_response_template.format(
            calculation_result=execution_output.strip(),
            final_answer_statement=final_answer_statement
        )

# Example Usage:
if __name__ == "__main__":
    assistant = SmartFinancialAssistant()
    
    query1 = "If I invest $500 monthly for 20 years with an average annual return of 7%, what will be the future value of my investment, and how much total interest will I earn?"
    response1 = assistant.process_financial_query(query1)
    print("\n--- Final Assistant Response ---")
    print(response1)
    print("\n" + "="*80 + "\n")

    query2 = "Calculate the future value if I put in 1000 every month for 10 years at 5.5% annual interest."
    response2 = assistant.process_financial_query(query2)
    print("\n--- Final Assistant Response ---")
    print(response2)
    print("\n" + "="*80 + "\n")

    query3 = "What is 2 plus 2?" # An unparseable query
    response3 = assistant.process_financial_query(query3)
    print("\n--- Final Assistant Response ---")
    print(response3)
    print("\n" + "="*80 + "\n")
