"""main.py - E-commerce Product Description Generator and Personalizer API
This file contains the consolidated code for the E-commerce Product Description Generator and Personalizer application.
It includes data models, LLM service abstraction, core logic, and the FastAPI application layer.
"""

from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, Field
from typing import List, Dict, Optional
import uuid
import time

# --- 1. Data Models & Mocks (data_models.py) ---

class ProductInfo(BaseModel):
    """Represents basic information about a product."""
    name: str = Field(..., example="Organic Cotton T-Shirt")
    category: str = Field(..., example="Apparel")
    features: List[str] = Field(..., example=["100% organic cotton", "Unisex fit", "Sustainable production"])

class UserProfile(BaseModel):
    """Represents a user's profile and preferences."""
    user_id: str = Field(..., example="user_123")
    preferences: List[str] = Field(..., example=["eco-friendly", "luxury", "budget-conscious"])

class GeneratedDescription(BaseModel):
    """Represents a product description generated by the LLM."""
    description_id: str = Field(..., example="desc_abc")
    text: str = Field(..., example="A comfortable and stylish organic cotton t-shirt...")

class PersonalizedDescription(BaseModel):
    """Represents a product description personalized for a specific user."""
    original_description_id: str = Field(..., example="desc_abc")
    user_id: str = Field(..., example="user_123")
    personalized_text: str = Field(..., example="For the eco-conscious shopper, this organic cotton t-shirt...")

# Mock Data for demonstration
MOCK_PRODUCTS: Dict[str, ProductInfo] = {
    "prod_001": ProductInfo(
        name="Handcrafted Leather Wallet",
        category="Accessories",
        features=["Full-grain leather", "Hand-stitched", "Multiple card slots", "RFID protection"]
    ),
    "prod_002": ProductInfo(
        name="Smart Home Security Camera",
        category="Electronics",
        features=["1080p HD video", "Motion detection", "Two-way audio", "Cloud storage"]
    ),
}

MOCK_USERS: Dict[str, UserProfile] = {
    "user_123": UserProfile(user_id="user_123", preferences=["luxury", "durable"]),
    "user_456": UserProfile(user_id="user_456", preferences=["eco-friendly", "innovative"]),
    "user_789": UserProfile(user_id="user_789", preferences=["budget-conscious", "practical"]),
}

MOCK_GENERATED_DESCRIPTIONS: Dict[str, GeneratedDescription] = {}
# --- End of Data Models & Mocks ---


# --- 2. LLM Service Abstraction (llm_service.py) ---

class LLMService:
    """Abstracts interactions with a Large Language Model.
    In a real application, this would integrate with a powerful LLM API (e.g., OpenAI, Hugging Face).
    """
    def __init__(self):
        # Placeholder for LLM initialization (e.g., loading a transformers pipeline)
        # For this example, we'll simulate LLM behavior with simple string manipulation.
        pass

    def _generate_base_prompt(self, product_info: ProductInfo) -> str:
        """Constructs a base prompt for product description generation."""
        features_str = ", ".join(product_info.features)
        return (
            f"Generate a detailed and appealing product description for an e-commerce item with the "
            f"following details:\n\nProduct Name: {product_info.name}\n"
            f"Category: {product_info.category}\n"
            f"Key Features: {features_str}\n\nDescription:"
        )

    def _generate_personalization_prompt(self, base_description: str, user_preferences: List[str]) -> str:
        """Constructs a prompt for personalizing a product description."""
        preferences_str = ", ".join(user_preferences)
        return (
            f"Refine the following product description to appeal to a user with these preferences: "
            f"{preferences_str}.\n\nOriginal Description: {base_description}\n\nPersonalized Description:"
        )

    def generate_description(self, product_info: ProductInfo) -> str:
        """Simulates generating a product description using an LLM."""
        print(f"[LLMService] Generating description for: {product_info.name}")
        prompt = self._generate_base_prompt(product_info)
        # Simulate LLM processing time and output
        time.sleep(0.5) # Simulate API call/inference time
        generated_text = (
            f"Introducing the {product_info.name}, a premium {product_info.category} "
            f"designed with excellence. Featuring {', '.join(product_info.features)}. "
            f"This description was augmented by an LLM based on minimal input."
        )
        return generated_text

    def personalize_description(self, base_description: str, user_preferences: List[str]) -> str:
        """Simulates personalizing a description using an LLM."""
        print(f"[LLMService] Personalizing description with preferences: {user_preferences}")
        prompt = self._generate_personalization_prompt(base_description, user_preferences)
        # Simulate LLM processing time and output
        time.sleep(0.3) # Simulate API call/inference time
        personalization_suffix = f"\n\nTailored for users who value {', '.join(user_preferences)}. "
        personalized_text = base_description + personalization_suffix + "This personalization was LLM-driven."
        return personalized_text

# --- End of LLM Service Abstraction ---


# --- 3. Core Logic (product_description_service.py) ---

class ProductDescriptionService:
    """Orchestrates product description generation and personalization."""
    def __init__(self, llm_service: LLMService):
        self.llm_service = llm_service

    def generate_product_description(self, product_info: ProductInfo) -> GeneratedDescription:
        """Generates a new product description using the LLM service."""
        description_text = self.llm_service.generate_description(product_info)
        new_description_id = str(uuid.uuid4())
        generated_desc = GeneratedDescription(
            description_id=new_description_id,
            text=description_text
        )
        MOCK_GENERATED_DESCRIPTIONS[new_description_id] = generated_desc
        return generated_desc

    def personalize_product_description(self, description_id: str, user_id: str) -> PersonalizedDescription:
        """Personalizes an existing product description for a specific user."""
        # Retrieve base description
        base_description_obj = MOCK_GENERATED_DESCRIPTIONS.get(description_id)
        if not base_description_obj:
            raise HTTPException(status_code=404, detail=f"Description with ID '{description_id}' not found.")
        base_description_text = base_description_obj.text

        # Retrieve user preferences
        user_profile = MOCK_USERS.get(user_id)
        if not user_profile:
            raise HTTPException(status_code=404, detail=f"User with ID '{user_id}' not found.")
        user_preferences = user_profile.preferences

        # Personalize using LLM service
        personalized_text = self.llm_service.personalize_description(
            base_description_text, user_preferences
        )

        return PersonalizedDescription(
            original_description_id=description_id,
            user_id=user_id,
            personalized_text=personalized_text
        )

# --- End of Core Logic ---


# --- 4. API Layer (main.py) ---

app = FastAPI(
    title="E-commerce LLM Product Description API",
    description="API for generating and personalizing e-commerce product descriptions using LLMs."
)

# Initialize services
llm_service_instance = LLMService()
product_description_service_instance = ProductDescriptionService(llm_service=llm_service_instance)

@app.post("/generate_description", response_model=GeneratedDescription, status_code=201)
async def generate_description_endpoint(product_info: ProductInfo):
    """Generate a new product description based on product information."""
    try:
        generated_desc = product_description_service_instance.generate_product_description(product_info)
        return generated_desc
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to generate description: {e}")

@app.post("/personalize_description", response_model=PersonalizedDescription)
async def personalize_description_endpoint(description_id: str, user_id: str):
    """Personalize an existing product description for a specific user."""
    try:
        personalized_desc = product_description_service_instance.personalize_product_description(description_id, user_id)
        return personalized_desc
    except HTTPException as e:
        raise e # Re-raise HTTPException from service layer
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to personalize description: {e}")


@app.get("/products", response_model=List[ProductInfo])
async def get_mock_products():
    """Retrieve available mock product information."""
    return list(MOCK_PRODUCTS.values())

@app.get("/users", response_model=List[UserProfile])
async def get_mock_users():
    """Retrieve available mock user profiles."""
    return list(MOCK_USERS.values())

@app.get("/descriptions", response_model=List[GeneratedDescription])
async def get_generated_descriptions():
    """Retrieve all currently generated mock descriptions."""
    return list(MOCK_GENERATED_DESCRIPTIONS.values())

# To run this application:
# 1. Save the code as `main.py`.
# 2. Install dependencies: `pip install fastapi "uvicorn[standard]" pydantic`
# 3. Run from your terminal: `uvicorn main:app --reload`
# 4. Access the API documentation at `http://127.0.0.1:8000/docs`

# --- End of API Layer ---