
import streamlit as st
import requests
import json

# --- FastAPI Backend (Conceptual - would run as a separate process) ---
# In a real scenario, this part would be in a file like `backend_app.py`
# and run using `uvicorn backend_app:app --reload`

# To simulate the backend without actually running FastAPI in this single file,
# we'll define the core logic that the FastAPI endpoint would use.
# For a true single file demonstration, you'd typically run Streamlit and FastAPI
# as separate processes, and Streamlit would make HTTP requests.
# For the purpose of this single file, we'll simulate the backend's logic directly
# as if Streamlit is calling it internally. In a production setup, replace
# the direct function calls with actual HTTP requests to a running FastAPI server.

# Mock Knowledge Base and LLM (Simplified for demonstration)
mock_medical_knowledge = [
    "Symptoms of influenza include fever, cough, sore throat, and body aches.",
    "Paracetamol is commonly used for pain relief and fever reduction.",
    "Diabetes symptoms include frequent urination, increased thirst, and unexplained weight loss.",
    "Metformin is a common medication for type 2 diabetes.",
    "Common cold symptoms are milder than flu and usually include a runny nose and sneezing.",
    "Drug interaction between Warfarin and Ibuprofen can increase bleeding risk.",
    "High blood pressure (hypertension) often has no symptoms but can be managed with medication and lifestyle changes."
]

def mock_vector_db_retrieve(query: str, top_k: int = 2) -> list[str]:
    """Simulates retrieval from a vector database based on query similarity."""
    # In a real application, this would involve embeddings and a vector search.
    # For this mock, we'll do a simple keyword-based 'retrieval'.
    retrieved_docs = []
    query_lower = query.lower()
    for doc in mock_medical_knowledge:
        if any(keyword in doc.lower() for keyword in query_lower.split()):
            retrieved_docs.append(doc)
    return retrieved_docs[:top_k] # Return top_k matching docs

def mock_llm_reasoning(patient_data: str, retrieved_context: list[str]) -> str:
    """Simulates LLM-based reasoning for diagnosis and treatment."""
    prompt_parts = [
        "Based on the following patient information and medical knowledge, provide a concise diagnostic aid:",
        "Patient Data: " + patient_data,
        "Medical Knowledge: " + " ".join(retrieved_context)
    ]
    full_prompt = "\n".join(prompt_parts)

    # Simulate LLM's response based on keywords from the prompt
    response = ""
    if "fever" in patient_data.lower() and "cough" in patient_data.lower():
        response += "Consider influenza or common cold. "
    if "urination" in patient_data.lower() and "thirst" in patient_data.lower():
        response += "Evaluate for diabetes. "
    if "warfarin" in patient_data.lower() and "ibuprofen" in patient_data.lower():
        response += "Warning: Potential drug interaction - increased bleeding risk. "
    if not response:
        response = "Further investigation may be required based on the provided details. Consult a specialist."

    return f"Diagnostic Aid: {response.strip()} (Generated by simulated LLM)"

# --- Streamlit Frontend ---
# This part would typically be in `frontend_app.py`

st.set_page_config(page_title="Unified Medical Diagnostic Aid", layout="wide")
st.title("🩺 Unified Medical Diagnostic Aid")
st.markdown("--- Patient Information ---")

patient_symptoms = st.text_area(
    "Enter Patient Symptoms (e.g., 'fever, cough, sore throat')",
    height=100,
    key="symptoms_input"
)

patient_history = st.text_area(
    "Enter Patient Medical History & Medications (e.g., 'history of diabetes, currently on Warfarin')",
    height=150,
    key="history_input"
)

if st.button("Get Diagnostic Aid", type="primary"):
    if patient_symptoms or patient_history:
        st.subheader("Generating Diagnostic Aid...")

        # Combine symptoms and history for the backend's query
        patient_full_data = f"Symptoms: {patient_symptoms}. History: {patient_history}"

        # --- Simulate Backend Call (Direct Function Calls for Single File Demo) ---
        # In a real setup, Streamlit would make an HTTP POST request to a running FastAPI server:
        # try:
        #     response = requests.post(
        #         "http://localhost:8000/diagnose", # Replace with your FastAPI backend URL
        #         json={
        #             "patient_data": patient_full_data
        #         }
        #     )
        #     response.raise_for_status() # Raise an exception for HTTP errors
        #     diagnostic_result = response.json().get("diagnostic_aid", "Error retrieving diagnosis.")
        # except requests.exceptions.ConnectionError:
        #     diagnostic_result = "Error: Could not connect to the backend server. Is FastAPI running?"
        # except requests.exceptions.RequestException as e:
        #     diagnostic_result = f"An error occurred during the request: {e}"

        # For this single-file demonstration, we directly call the simulated backend logic:
        retrieved_info = mock_vector_db_retrieve(patient_full_data)
        diagnostic_result = mock_llm_reasoning(patient_full_data, retrieved_info)

        st.subheader("Diagnostic Aid:")
        st.success(diagnostic_result)

        st.subheader("Retrieved Medical Knowledge:")
        if retrieved_info:
            for doc in retrieved_info:
                st.info(f"- {doc}")
        else:
            st.info("No specific relevant knowledge retrieved for the given input.")

    else:
        st.warning("Please enter patient symptoms or medical history to get a diagnosis.")

st.markdown("---")
st.info("Disclaimer: This is a prototype AI diagnostic aid and should not replace professional medical advice.")

# Instructions to run (for a conceptual single file setup):
# 1. Save this code as `main_medical_diagnostic_aid.py`
# 2. Install necessary libraries: `pip install streamlit requests` (FastAPI and Uvicorn would be needed for a real backend)
# 3. To run the Streamlit app: `streamlit run main_medical_diagnostic_aid.py`
# (Note: The FastAPI part is simulated for this single file. In a real application,
#  you would have a separate `backend_app.py` for FastAPI and run it with `uvicorn`.)
