import streamlit as st
import numpy as np
import pandas as pd
from scipy.optimize import minimize
from scipy.stats import norm
import io
import contextlib

# --- 1. LLM Simulation Functions (Placeholder for actual LLM API calls) ---

def simulate_llm_code_generation(financial_goals, current_investments, risk_tolerance):
    """
    Simulates an LLM generating Python code for financial computations.
    In a real application, this would involve prompting an LLM (e.g., OpenAI GPT-4)
    to generate the code based on the user's input.
    """
    st.info("LLM is generating financial computation code...")
    # Example: Simple portfolio optimization and Monte Carlo simulation code
    # This code would be dynamically generated by a real LLM
    generated_code = f"""
import numpy as np
import pandas as pd
from scipy.optimize import minimize
from scipy.stats import norm

def portfolio_optimization(expected_returns, cov_matrix, risk_free_rate=0.01):
    num_assets = len(expected_returns)
    args = (expected_returns, cov_matrix, risk_free_rate)

    # Function to calculate portfolio return
    def portfolio_return(weights, expected_returns):
        return np.sum(expected_returns * weights)

    # Function to calculate portfolio volatility
    def portfolio_volatility(weights, cov_matrix):
        return np.sqrt(np.dot(weights.T, np.dot(cov_matrix, weights)))

    # Objective function for minimizing volatility (for a given return target)
    def min_volatility(weights, expected_returns, cov_matrix):
        return portfolio_volatility(weights, cov_matrix)

    # Constraints: weights sum to 1, and each weight is between 0 and 1
    constraints = ({'type': 'eq', 'fun': lambda x: np.sum(x) - 1})
    bounds = tuple((0, 1) for asset in range(num_assets))
    initial_weights = num_assets * [1. / num_assets]

    # Optimize for minimum volatility portfolio
    optimal_weights_min_vol = minimize(min_volatility, initial_weights, args=(expected_returns, cov_matrix),
                                    method='SLSQP', bounds=bounds, constraints=constraints)

    min_vol_portfolio = {{
        'weights': optimal_weights_min_vol.x,
        'return': portfolio_return(optimal_weights_min_vol.x, expected_returns),
        'volatility': portfolio_volatility(optimal_weights_min_vol.x, cov_matrix)
    }}

    return min_vol_portfolio

def monte_carlo_simulation(initial_investment, expected_annual_return, annual_volatility, years=10, num_simulations=10000):
    dt = 1/252  # Assuming 252 trading days in a year
    num_days = years * 252
    daily_returns = np.random.normal(expected_annual_return/252, annual_volatility/np.sqrt(252), (num_days, num_simulations))
    
    price_paths = np.zeros_like(daily_returns)
    price_paths[0] = initial_investment
    for t in range(1, num_days):
        price_paths[t] = price_paths[t-1] * (1 + daily_returns[t])

    final_portfolios = price_paths[-1]
    
    results = {{
        'median_final_value': np.median(final_portfolios),
        'percentile_5th': np.percentile(final_portfolios, 5),
        'percentile_95th': np.percentile(final_portfolios, 95),
        'loss_probability': np.sum(final_portfolios < initial_investment) / num_simulations
    }}
    return results


# Placeholder data for demonstration (in a real app, this would come from a data source)
# Asset names: [Stock A, Stock B, Bond C, Real Estate D]
asset_names = ["Tech Stocks", "Value Stocks", "Bonds", "Real Estate"]
expected_returns_data = np.array([0.12, 0.08, 0.04, 0.06]) # Example annual returns
cov_matrix_data = np.array([
    [0.04, 0.01, 0.005, 0.002],
    [0.01, 0.03, 0.003, 0.001],
    [0.005, 0.003, 0.01, 0.001],
    [0.002, 0.001, 0.001, 0.02]
]) # Example covariance matrix


# --- Execute calculations ---

# Portfolio Optimization
min_vol_portfolio_results = portfolio_optimization(expected_returns_data, cov_matrix_data)

# Monte Carlo Simulation (using a blend of returns/volatility based on risk tolerance)
# Simplified mapping: higher risk tolerance -> higher expected return, higher volatility
expected_annual_return_mc = 0.05 + ({risk_tolerance} / 10.0) * 0.07 # Adjust based on risk tolerance
annual_volatility_mc = 0.10 + ({risk_tolerance} / 10.0) * 0.15 # Adjust based on risk tolerance
monte_carlo_results = monte_carlo_simulation({current_investments}, expected_annual_return_mc, annual_volatility_mc, years=10)


# Store results in a dictionary to be returned
_computation_results = {{
    'min_vol_portfolio': min_vol_portfolio_results,
    'asset_names': asset_names,
    'monte_carlo': monte_carlo_results
}}
"""
    return generated_code

def execute_generated_code(code_string):
    """
    Executes the generated Python code securely and captures its output.
    """
    st.info("Executing generated financial code...")
    local_vars = {}
    try:
        # Redirect stdout to capture print statements, if any
        # In this specific case, the generated code assigns to _computation_results
        # so stdout redirection is less critical but good practice for general exec()
        with contextlib.redirect_stdout(io.StringIO()) as f:
            exec(code_string, {}, local_vars)
        # The generated code assigns results to a specific variable name `_computation_results`
        if '_computation_results' in local_vars:
            return local_vars['_computation_results']
        else:
            st.error("Generated code did not produce expected '_computation_results'.")
            return None
    except Exception as e:
        st.error(f"Error executing code: {e}")
        return None

def simulate_llm_synthesis(financial_results, financial_goals, current_investments, risk_tolerance):
    """
    Simulates an LLM synthesizing the numerical results into a natural language strategy.
    In a real application, this would be another LLM call with the results and user inputs.
    """
    st.info("LLM is synthesizing the investment strategy...")
    if not financial_results:
        return "Could not generate an investment strategy due to computation errors."

    strategy_output = []
    strategy_output.append("### Personalized Investment Strategy and Risk Assessment\n")
    strategy_output.append(f"Based on your financial goals: '{financial_goals}', current investment of ${current_investments:,.2f}, and a risk tolerance of {risk_tolerance}/10, here's a detailed strategy.\n")

    # Portfolio Optimization Results
    strategy_output.append("#### 1. Optimal Asset Allocation (Minimum Volatility Portfolio)\n")
    min_vol_portfolio = financial_results['min_vol_portfolio']
    asset_names = financial_results['asset_names']
    strategy_output.append("To achieve a portfolio with minimized volatility for a given level of return, consider the following allocation:\n")
    for i, weight in enumerate(min_vol_portfolio['weights']):
        strategy_output.append(f"- **{asset_names[i]}**: {weight:.2%}\n")
    strategy_output.append(f"This optimized portfolio is expected to have an annual return of {min_vol_portfolio['return']:.2%} with an annual volatility of {min_vol_portfolio['volatility']:.2%}.\n")

    # Monte Carlo Simulation Results
    strategy_output.append("#### 2. Future Growth Projections and Risk Assessment (Monte Carlo Simulation)\n")
    monte_carlo_results = financial_results['monte_carlo']
    strategy_output.append(f"Over the next 10 years, with your current investment and risk profile, our simulations project the following outcomes:\n")
    strategy_output.append(f"- **Median Projected Value**: ${monte_carlo_results['median_final_value']:.2f}\n")
    strategy_output.append(f"- There is a 5% chance your investment could fall below **${monte_carlo_results['percentile_5th']:.2f}**.\n")
    strategy_output.append(f"- There is a 5% chance your investment could exceed **${monte_carlo_results['percentile_95th']:.2f}**.\n")
    strategy_output.append(f"- The probability of experiencing a loss (ending below your initial investment) is approximately **{monte_carlo_results['loss_probability']:.2%}**. \n")
    strategy_output.append("This indicates the potential range of outcomes, helping you understand the inherent risks and rewards.\n")

    strategy_output.append("#### 3. Recommendations\n")
    # Example recommendation logic based on risk tolerance and simulation results
    if risk_tolerance >= 7:
        strategy_output.append("Given your high risk tolerance, the strategy leans towards growth-oriented assets. You might consider exploring additional higher-growth opportunities, but always ensure diversification.\n")
    elif risk_tolerance >= 4:
        strategy_output.append("Your moderate risk tolerance suggests a balanced approach. The recommended portfolio aims for a good balance between growth and stability. Regular rebalancing is advised.\n")
    else:
        strategy_output.append("With a lower risk tolerance, capital preservation is key. The portfolio emphasizes stability. Consider fixed-income assets and regular review of your financial plan.\n")

    strategy_output.append("\n*Disclaimer: This is a simulated investment strategy for demonstration purposes only and not financial advice. Consult a professional financial advisor before making any investment decisions.*")

    return "\n".join(strategy_output)

# --- 2. Streamlit User Interface ---

st.set_page_config(layout="wide", page_title="Personalized Investment Strategy Generator")
st.title("📈 Personalized Investment Strategy Generator")
st.markdown("--- Generates investment strategies using Code-Assisted Reasoning (CAR) ---")

st.sidebar.header("Your Financial Profile")

financial_goals = st.sidebar.text_area(
    "What are your financial goals? (e.g., 'Save for retirement in 20 years', 'Buy a house in 5 years', 'Grow wealth aggressively')",
    "Save for retirement in 20 years, grow wealth steadily."
)

current_investments = st.sidebar.number_input(
    "Current Investment Amount ($)",
    min_value=1000, max_value=10000000, value=100000, step=1000
)

risk_tolerance = st.sidebar.slider(
    "Your Risk Tolerance (1 = Very Low, 10 = Very High)",
    min_value=1, max_value=10, value=5
)

st.sidebar.markdown("---")

if st.sidebar.button("Generate My Investment Strategy"):
    if financial_goals and current_investments:
        with st.spinner("Generating your personalized strategy..."):
            # Step 1: LLM generates financial computation code
            code_to_execute = simulate_llm_code_generation(financial_goals, current_investments, risk_tolerance)

            # Step 2: Execute the generated code
            computation_results = execute_generated_code(code_to_execute)

            # Step 3: LLM synthesizes results into natural language strategy
            if computation_results:
                final_strategy = simulate_llm_synthesis(computation_results, financial_goals, current_investments, risk_tolerance)
                st.markdown(final_strategy)
            else:
                st.error("Failed to obtain computation results. Please try again.")
    else:
        st.warning("Please fill in all financial profile details.")

st.markdown("\n---")
st.write("This application demonstrates the **Code-Assisted Reasoning (CAR) Pattern** by simulating an LLM that generates and executes Python code for precise financial calculations before synthesizing the results into a natural language investment strategy.")

# To run this Streamlit app:
# 1. Save the code as `investment_strategy_generator.py`
# 2. Open your terminal/command prompt.
# 3. Navigate to the directory where you saved the file.
# 4. Run `streamlit run investment_strategy_generator.py`
# 5. Your browser will open with the application. Enjoy!
