from pydantic import BaseModel, Field
from typing import List, Optional

class PatientCase(BaseModel):
    """Represents a patient's medical case with relevant information."""
    case_id: str = Field(..., description="Unique identifier for the patient case.")
    symptoms: List[str] = Field(..., description="List of reported symptoms.")
    medical_history: List[str] = Field(default_factory=list, description="Patient's relevant medical history.")
    test_results: List[str] = Field(default_factory=list, description="List of available test results.")
    notes: Optional[str] = Field(None, description="Any additional notes or observations.")

class ReasoningStep(BaseModel):
    """Represents a single step in the LLM's diagnostic reasoning process."""
    step_number: int = Field(..., description="The sequential number of the reasoning step.")
    prompt_used: str = Field(..., description="The prompt given to the LLM for this step.")
    llm_output: str = Field(..., description="The raw output from the LLM for this step.")
    interpretation: str = Field(..., description="Human-readable interpretation of the LLM's output.")
    confidence: Optional[float] = Field(None, description="Confidence score for this specific step's output (0.0 to 1.0).")

class ProposedDiagnosis(BaseModel):
    """Represents a potential diagnosis with supporting evidence."""
    diagnosis_name: str = Field(..., description="The name of the proposed diagnosis.")
    supporting_evidence: List[str] = Field(default_factory=list, description="Facts from the patient case or medical knowledge supporting this diagnosis.")
    counter_evidence: List[str] = Field(default_factory=list, description="Facts contradicting this diagnosis.")
    confidence_score: float = Field(..., description="Overall confidence in this proposed diagnosis (0.0 to 1.0).")

class DiagnosisReport(BaseModel):
    """The final comprehensive report generated by the AI assistant."""
    patient_case: PatientCase = Field(..., description="The original patient case processed.")
    reasoning_path: List[ReasoningStep] = Field(default_factory=list, description="The detailed, step-by-step reasoning process.")
    initial_diagnoses: List[ProposedDiagnosis] = Field(default_factory=list, description="List of diagnoses proposed by the LLM before verification.")
    verified_diagnoses: List[ProposedDiagnosis] = Field(default_factory=list, description="List of diagnoses after self-consistency and external verification.")
    final_diagnosis_summary: str = Field(..., description="A concise summary of the most likely diagnosis/diagnoses.")
    recommendations: List[str] = Field(default_factory=list, description="Recommendations for further tests or specialist consultations.")
    disclaimer: str = Field(..., description="Standard disclaimer about AI assistance and professional medical advice.")
