from pydantic import BaseModel, Field
from typing import List, Dict, Any, Optional
import os
from langchain_openai import ChatOpenAI
from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder
from dotenv import load_dotenv

load_dotenv()

class WorkingMemory(BaseModel):
    user_query: str = Field(default="", description="Current user input.")
    external_evidence: Dict[str, Any] = Field(default_factory=dict, description="Consolidated external evidence (e.g., product data, order history).")
    llm_candidate_responses: List[str] = Field(default_factory=list, description="Potential responses generated by the LLM.")
    utility_scores: List[float] = Field(default_factory=list, description="Utility scores for candidate responses.")
    verbalized_feedback: List[str] = Field(default_factory=list, description="Verbalized feedback on responses.")
    dialog_history: List[Dict[str, str]] = Field(default_factory=list, description="Complete history of the dialogue.")

class PromptEngine:
    def __init__(self, system_message: str = "You are an intelligent customer support assistant for an e-commerce platform. Provide helpful and concise answers."):
        self.system_message = system_message

    def construct_prompt(self, memory: WorkingMemory) -> ChatPromptTemplate:
        messages = [
            ("system", self.system_message),
            MessagesPlaceholder(variable_name="chat_history"),
            ("human", "{input}")
        ]
        
        # Add external evidence to system message if available
        if memory.external_evidence:
            evidence_str = "\n\nRelevant information: " + str(memory.external_evidence)
            messages[0] = ("system", self.system_message + evidence_str)

        prompt = ChatPromptTemplate.from_messages(messages)
        return prompt

class Policy:
    def decide_action(self, memory: WorkingMemory) -> str:
        if memory.llm_candidate_responses:
            # Simple policy: pick the response with the highest utility score
            if memory.utility_scores and len(memory.utility_scores) == len(memory.llm_candidate_responses):
                best_response_idx = memory.utility_scores.index(max(memory.utility_scores))
                return memory.llm_candidate_responses[best_response_idx]
            else:
                # Fallback if no utility scores or mismatch
                return memory.llm_candidate_responses[0]
        
        return "I am not sure how to respond to that. Can you please rephrase?"

class ChatbotOrchestrator:
    def __init__(self, model_name: str = "gpt-4"):
        self.llm = ChatOpenAI(model_name=model_name, temperature=0.7)
        self.prompt_engine = PromptEngine()
        self.policy = Policy()
        self.memory = WorkingMemory()

    def process_user_input(self, user_input: str) -> str:
        # Update working memory with current user query
        self.memory.user_query = user_input
        self.memory.dialog_history.append({"role": "user", "content": user_input})

        # Simulate fetching external evidence (replace with actual logic)
        if "order status" in user_input.lower():
            self.memory.external_evidence = {"order_id": "12345", "status": "shipped", "delivery_date": "2023-11-20"}
        elif "product details" in user_input.lower() and "laptop" in user_input.lower():
            self.memory.external_evidence = {"product_name": "Gaming Laptop", "price": "$1500", "stock": "in stock"}
        else:
            self.memory.external_evidence = {}

        # Construct prompt
        prompt = self.prompt_engine.construct_prompt(self.memory)
        
        # Prepare chat history for Langchain
        chat_history_for_llm = [
            (entry["role"], entry["content"])
            for entry in self.memory.dialog_history[:-1] # Exclude current user query as it's passed as 'input'
        ]

        # Invoke LLM
        try:
            chain = prompt | self.llm
            response_obj = chain.invoke({"chat_history": chat_history_for_llm, "input": user_input})
            llm_response_content = response_obj.content
            
            # Update working memory with LLM candidate response (simplified for demonstration)
            self.memory.llm_candidate_responses = [llm_response_content]
            self.memory.utility_scores = [0.8] # Simulate a utility score
            self.memory.verbalized_feedback = [] # No feedback in this simplified example

            # Policy decides the final response
            final_response = self.policy.decide_action(self.memory)
            self.memory.dialog_history.append({"role": "assistant", "content": final_response})
            
            return final_response

        except Exception as e:
            print(f"Error during LLM invocation: {e}")
            return "I apologize, but I'm having trouble connecting right now. Please try again later."


if __name__ == "__main__":
    print("E-commerce Customer Support Chatbot (type 'exit' to quit)")
    chatbot = ChatbotOrchestrator()

    while True:
        user_input = input("You: ")
        if user_input.lower() == 'exit':
            break

        response = chatbot.process_user_input(user_input)
        print(f"Bot: {response}")
        print("\n--- Current Working Memory ---")
        print(chatbot.memory.model_dump_json(indent=2))
        print("------------------------------\n")
