import pandas as pd
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

class EvaluationFramework:
    def __init__(self, metrics=None):
        self.metrics = metrics if metrics is not None else [
            "accuracy", "precision", "recall", "f1"
        ]
        self.results = []

    def evaluate_response(self, predicted_intent, expected_intent):
        """
        Compares a predicted intent with the expected intent.
        For a real chatbot, this would involve more sophisticated NLP evaluation.
        """
        return predicted_intent == expected_intent

    def run_evaluation(self, test_data):
        """
        Runs the evaluation across a dataset of test queries.
        test_data is expected to be a list of dictionaries, each with:
        - 'query': original customer query
        - 'predicted_response': response generated by the LLM
        - 'expected_response': ideal response
        - 'predicted_intent': intent extracted from LLM response (or predicted by system)
        - 'expected_intent': true intent of the query
        """
        true_intents = [item['expected_intent'] for item in test_data]
        predicted_intents = [item['predicted_intent'] for item in test_data]

        # Simple evaluation based on exact intent match for demonstration
        # In a real scenario, NLP metrics like ROUGE, BLEU, or semantic similarity would be used for responses.
        correct_predictions = 0
        for i in range(len(test_data)):
            if self.evaluate_response(predicted_intents[i], true_intents[i]):
                correct_predictions += 1
        
        accuracy = correct_predictions / len(test_data) if test_data else 0
        
        # For other metrics, we'd need a more robust way to map predicted_response to predicted_intent
        # For now, just using accuracy as the primary metric based on intent matching.
        print(f"\n--- Evaluation Results ---")
        print(f"Total Queries: {len(test_data)}")
        print(f"Correct Intent Predictions: {correct_predictions}")
        print(f"Accuracy (Intent Matching): {accuracy:.4f}")

        # If we had multiple classes and wanted to calculate precision, recall, f1
        # from sklearn.metrics import classification_report
        # print("\nClassification Report:")
        # print(classification_report(true_intents, predicted_intents, zero_division=0))

        return {"accuracy": accuracy}

    def record_experiment_result(self, strategy_name, metric_values):
        """
        Records the results of an experiment with a specific ordering strategy.
        """
        result = {"strategy": strategy_name}
        result.update(metric_values)
        self.results.append(result)
        print(f"Recorded experiment result for {strategy_name}: {metric_values}")

    def get_all_results(self):
        """
        Returns all recorded experiment results.
        """
        return pd.DataFrame(self.results)

if __name__ == '__main__':
    eval_framework = EvaluationFramework()

    # Example test data
    sample_test_data = [
        {
            'query': 'Where is my order?',
            'predicted_response': 'Your order is being processed.',
            'expected_response': 'Your order is on its way.',
            'predicted_intent': 'order_status',
            'expected_intent': 'order_status'
        },
        {
            'query': 'I want to return this shirt.',
            'predicted_response': 'Please visit our returns page.',
            'expected_response': 'Initiate a return online.',
            'predicted_intent': 'product_return',
            'expected_intent': 'product_return'
        },
        {
            'query': 'What is product B?',
            'predicted_response': 'I can help with product details.',
            'expected_response': 'Product B is a smart device.',
            'predicted_intent': 'product_inquiry',
            'expected_intent': 'product_inquiry'
        },
        {
            'query': 'Can I track my delivery?',
            'predicted_response': 'Your package is on its way.',
            'expected_response': 'Please provide your order ID.',
            'predicted_intent': 'order_status',
            'expected_intent': 'order_status'
        },
        {
            'query': 'How to get a refund?',
            'predicted_response': 'Visit the returns section.',
            'expected_response': 'Refunds are processed in 7 days.',
            'predicted_intent': 'product_return',
            'expected_intent': 'general_inquiry' # Simulate an incorrect prediction
        },
    ]

    # Run evaluation and record results
    results = eval_framework.run_evaluation(sample_test_data)
    eval_framework.record_experiment_result("Random Ordering", results)

    # Simulate another experiment
    sample_test_data[4]['predicted_intent'] = 'product_return' # Fix the incorrect prediction
    results_improved = eval_framework.run_evaluation(sample_test_data)
    eval_framework.record_experiment_result("Semantic Ordering", results_improved)

    # Print all recorded results
    print("\n--- All Experiment Results ---")
    print(eval_framework.get_all_results())
