class UtilityModule:
    """Simulates the generation of automated feedback for LLM responses.

    In a real system, this would involve evaluation metrics, user ratings,
    or comparison with desired outputs.
    """

    def generate_feedback(self, llm_response: str, user_query: str) -> str:
        """Generates simulated feedback based on the LLM's response.

        Args:
            llm_response: The response generated by the LLM.
            user_query: The original user query.

        Returns:
            A string containing automated feedback.
        """
        feedback = []

        if "I cannot provide" in llm_response or "I don't have information" in llm_response:
            feedback.append("Feedback: The LLM indicated a lack of information or inability to assist. Consider providing more context or rephrasing the query.")
        elif "order status" in user_query.lower() and "Shipped" in llm_response:
            feedback.append("Feedback: Successfully provided order status. Response seems accurate.")
        elif "return policy" in user_query.lower() and "30 days" in llm_response:
            feedback.append("Feedback: Correctly referenced the return policy. Response is factual.")
        elif "price" in user_query.lower() and "$" in llm_response:
            feedback.append("Feedback: Included price information. Relevant to query.")
        elif len(llm_response.split()) < 10:
            feedback.append("Feedback: Response might be too brief. Could benefit from more detail.")
        elif "helpful" in llm_response.lower() or "glad to assist" in llm_response.lower():
            feedback.append("Feedback: LLM response has a positive and helpful tone.")
        else:
            feedback.append("Feedback: General positive sentiment. Response seems relevant.")

        return " ".join(feedback)


# main.py content

# To run this example, ensure you have the prompt_engine.py and knowledge_consolidator.py
# files in the same directory or adjust the imports accordingly.

# Simulating the LLM response - in a real application, this would be an actual API call
def simulate_llm_response(prompt: str) -> str:
    """A placeholder function to simulate an LLM's response."""
    print(f"\n--- LLM Input Prompt ---\n{prompt}\n") # For demonstration, show the full prompt
    # Very basic simulation: look for keywords and provide a canned response
    if "order status ORD123" in prompt:
        return "Your order ORD123 for t-shirt is Shipped."
    elif "jeans stock" in prompt:
        return "Jeans are available in M, L, XL."
    elif "return policy" in prompt:
        return "Our return policy allows returns within 30 days of purchase with a receipt. Items must be unworn and in original packaging."
    elif "hi" in prompt.lower() or "hello" in prompt.lower():
        return "Hello! How can I assist you with your FashionFusion order today?"
    elif "product T-shirt" in prompt:
        return "The T-shirt (ID: P101) is priced at $25 and available in S, M, L."
    else:
        return "I'm sorry, I couldn't find specific information for that. Can you please provide more details?"


class PromptEngine:
    """Manages the dynamic construction of prompts for the LLM."""

    def __init__(self, base_instructions: str):
        self.base_instructions = base_instructions

    def build_prompt(
        self,
        user_query: str,
        dialog_history: list[str],
        external_evidence: str = "",
        automated_feedback: str = "",
    ) -> str:
        """Constructs a comprehensive prompt for the LLM.

        Args:
            user_query: The current query from the user.
            dialog_history: A list of previous turns in the conversation.
            external_evidence: Consolidated relevant information from external sources.
            automated_feedback: Feedback from the utility module for refinement.

        Returns:
            A dynamically constructed prompt string.
        """
        prompt_parts = []
        prompt_parts.append(self.base_instructions)
        prompt_parts.append("\n--- Dialog History ---")
        if dialog_history:
            prompt_parts.extend(dialog_history)
        else:
            prompt_parts.append("No prior conversation.")

        if external_evidence and "No specific external evidence found" not in external_evidence:
            prompt_parts.append("\n--- External Knowledge ---")
            prompt_parts.append(external_evidence)

        if automated_feedback:
            prompt_parts.append("\n--- Previous Interaction Feedback ---")
            prompt_parts.append(automated_feedback)

        prompt_parts.append("\n--- Current User Query ---")
        prompt_parts.append(user_query)

        prompt_parts.append("\n--- Your Response ---")

        return "\n".join(prompt_parts)


class KnowledgeConsolidator:
    """Simulates fetching and consolidating external evidence for the LLM.

    In a real-world scenario, this would interact with databases, APIs, etc.
    """

    def __init__(self):
        # Dummy data for demonstration
        self.product_catalog = {
            "t-shirt": {"id": "P101", "price": "$25", "stock": "Available in S, M, L"},
            "jeans": {"id": "P102", "price": "$50", "stock": "Available in M, L, XL"},
            "dress": {"id": "P103", "price": "$75", "stock": "Limited stock in S"},
        }
        self.order_database = {
            "ORD123": {"customer": "Alice", "item": "t-shirt", "status": "Shipped"},
            "ORD124": {"customer": "Bob", "item": "jeans", "status": "Processing"},
        }
        self.policy_docs = {
            "returns": "Our return policy allows returns within 30 days of purchase with a receipt. Items must be unworn and in original packaging.",
            "shipping": "Standard shipping takes 5-7 business days. Express shipping is available for an extra charge.",
        }

    def get_evidence(self, query: str) -> str:
        """Fetches and consolidates relevant information based on the user's query.

        Args:
            query: The user's query to determine what evidence is needed.

        Returns:
            A string containing consolidated external evidence.
        """
        evidence_parts = []

        # Simulate checking for product information
        for product, details in self.product_catalog.items():
            if product in query.lower():
                evidence_parts.append(f"Product Info: {product.capitalize()} (ID: {details['id']}, Price: {details['price']}, Stock: {details['stock']})")

        # Simulate checking for order information
        if "order status" in query.lower() or "track my order" in query.lower():
            # Check for specific order ID first
            found_order = False
            for order_id, details in self.order_database.items():
                if order_id in query:
                    evidence_parts.append(f"Order Status: Order {order_id} for {details['item']} is {details['status']}.")
                    found_order = True
                    break
            if not found_order and ("order status" in query.lower() or "track my order" in query.lower()): # If no specific ID, ask for it
                evidence_parts.append("Please provide your order ID to check the status.")


        # Simulate checking for policy documents
        if "return policy" in query.lower() or "how to return" in query.lower():
            evidence_parts.append(f"Return Policy: {self.policy_docs['returns']}")
        if "shipping" in query.lower() or "delivery time" in query.lower():
            evidence_parts.append(f"Shipping Policy: {self.policy_docs['shipping']}")

        if not evidence_parts:
            return "No specific external evidence found for this query."
        return "\n".join(evidence_parts)


def run_customer_support_ai():
    """Main function to run the customer support AI assistant."""
    print("FashionFusion Customer Support AI Assistant")
    print("Type 'exit' or 'quit' to end the conversation.")
    print("--------------------------------------------------")

    base_instructions = (
        "Act as a helpful and friendly customer support agent for FashionFusion, an e-commerce platform."
        "Provide accurate information based on the context given."
    )

    prompt_engine = PromptEngine(base_instructions)
    knowledge_consolidator = KnowledgeConsolidator()
    utility_module = UtilityModule()

    dialog_history = []
    previous_feedback = ""

    while True:
        user_query = input("\nYou: ")
        if user_query.lower() in ["exit", "quit"]:
            print("FashionFusion AI: Goodbye!")
            break

        external_evidence = knowledge_consolidator.get_evidence(user_query)
        print(f"\n--- Debug: External Evidence ---\n{external_evidence}\n")

        full_prompt = prompt_engine.build_prompt(
            user_query,
            dialog_history,
            external_evidence,
            previous_feedback
        )

        llm_response = simulate_llm_response(full_prompt)
        current_feedback = utility_module.generate_feedback(llm_response, user_query)

        print(f"FashionFusion AI: {llm_response}")
        print(f"--- Automated Feedback for last turn ---\n{current_feedback}")

        # Update dialog history for the next turn
        dialog_history.append(f"User: {user_query}")
        dialog_history.append(f"AI: {llm_response}")
        previous_feedback = current_feedback # Use this feedback for the next prompt


if __name__ == "__main__":
    run_customer_support_ai()
