from abc import ABC, abstractmethod

class AbstractLLM(ABC):
    """
    Abstract base class for all Large Language Model providers.
    Defines the unified interface for interacting with any LLM.
    """
    @abstractmethod
    def generate_response(self, prompt: str) -> str:
        """
        Generates a text response based on the given prompt.
        """
        pass

class GPTLLM(AbstractLLM):
    """
    Concrete implementation for OpenAI's GPT models.
    Mocks API calls for demonstration purposes.
    """
    def __init__(self, api_key: str):
        self.api_key = api_key
        print(f"Initializing GPT LLM with API Key: {'*' * (len(api_key) - 4)}{api_key[-4:]}")
        # In a real application, you would initialize the OpenAI client here
        # from openai import OpenAI
        # self.client = OpenAI(api_key=api_key)

    def generate_response(self, prompt: str) -> str:
        print(f"[GPT LLM] Processing prompt: '{prompt[:50]}...'")
        # Simulate an API call to OpenAI GPT
        # response = self.client.chat.completions.create(
        #     model="gpt-3.5-turbo",
        #     messages=[{"role": "user", "content": prompt}]
        # )
        # return response.choices[0].message.content
        
        # Mock response for demonstration
        if "product information" in prompt.lower():
            return f"GPT: Sure, for '{prompt.split(':')[-1].strip()}', I can tell you it's a high-quality item with excellent reviews. What specific details are you looking for?"
        elif "order tracking" in prompt.lower():
            return "GPT: To track your order, please provide your order number. I'll then look up its current status for you."
        return f"GPT: I'm processing your request using GPT. Your query was: '{prompt}'. How else can I assist you today?"

class GeminiLLM(AbstractLLM):
    """
    Concrete implementation for Google's Gemini models.
    Mocks API calls for demonstration purposes.
    """
    def __init__(self, api_key: str):
        self.api_key = api_key
        print(f"Initializing Gemini LLM with API Key: {'*' * (len(api_key) - 4)}{api_key[-4:]}")
        # In a real application, you would initialize the Google Generative AI client here
        # import google.generativeai as genai
        # genai.configure(api_key=api_key)
        # self.model = genai.GenerativeModel('gemini-pro')

    def generate_response(self, prompt: str) -> str:
        print(f"[Gemini LLM] Processing prompt: '{prompt[:50]}...'")
        # Simulate an API call to Google Gemini
        # response = self.model.generate_content(prompt)
        # return response.text
        
        # Mock response for demonstration
        if "product information" in prompt.lower():
            return f"Gemini: Absolutely! Regarding '{prompt.split(':')[-1].strip()}', this product is known for its durability and innovative features. Do you have any specific questions about it?"
        elif "order tracking" in prompt.lower():
            return "Gemini: Please provide your order ID so I can fetch the latest tracking details for your shipment."
        return f"Gemini: I am responding to your query using Gemini. The prompt was: '{prompt}'. Let me know if you need further assistance!"

class LlamaLLM(AbstractLLM):
    """
    Concrete implementation for Llama (e.g., via Hugging Face or local deployment).
    Mocks API calls for demonstration purposes.
    """
    def __init__(self, api_key: str):
        self.api_key = api_key # Llama might not always use a traditional API key, but a token or local path
        print(f"Initializing Llama LLM with API Key/Token: {'*' * (len(api_key) - 4)}{api_key[-4:]}")
        # In a real application, you might load a local model or use a service like Replicate/Hugging Face Inference API
        # from transformers import pipeline
        # self.pipe = pipeline("text-generation", model="meta-llama/Llama-2-7b-chat-hf", token=api_key)

    def generate_response(self, prompt: str) -> str:
        print(f"[Llama LLM] Processing prompt: '{prompt[:50]}...'")
        # Simulate an API call/local inference for Llama
        # sequences = self.pipe(prompt, max_new_tokens=100, do_sample=True, top_k=10, num_return_sequences=1, eos_token_id=self.pipe.tokenizer.eos_token_id)
        # return sequences[0]['generated_text']
        
        # Mock response for demonstration
        if "product information" in prompt.lower():
            return f"Llama: Hello! For details on '{prompt.split(':')[-1].strip()}', it's a very popular item. What specific features or specifications would you like to know?"
        elif "order tracking" in prompt.lower():
            return "Llama: I can help with order tracking. Could you please share your order reference number?"
        return f"Llama: This response is generated by Llama. Your input was: '{prompt}'. Feel free to ask more questions."

class LLMFactory:
    """
    Factory class to create instances of different LLM providers.
    """
    @staticmethod
    def get_llm(provider_name: str, api_key: str) -> AbstractLLM:
        """
        Returns an instance of an LLM provider based on the given name.
        Args:
            provider_name (str): The name of the LLM provider (e.g., "GPT", "Gemini", "Llama").
            api_key (str): The API key or token for the specific LLM provider.
        Returns:
            AbstractLLM: An instance of the requested LLM provider.
        Raises:
            ValueError: If an unsupported LLM provider name is given.
        """
        provider_name = provider_name.lower()
        if provider_name == "gpt":
            return GPTLLM(api_key)
        elif provider_name == "gemini":
            return GeminiLLM(api_key)
        elif provider_name == "llama":
            return LlamaLLM(api_key)
        else:
            raise ValueError(f"Unsupported LLM provider: {provider_name}")


if __name__ == '__main__':
    # Example Usage:
    print("--- Demonstrating LLM Abstraction Layer ---")

    # In a real app, API keys would come from environment variables or a secure config
    MOCK_GPT_KEY = "sk-mock-gpt-key-1234567890"
    MOCK_GEMINI_KEY = "AIzaSyBmockGeminiKey1234567890"
    MOCK_LLAMA_KEY = "hf_mock_llama_token_1234567890"

    print("\n--- Using GPT LLM ---")
    gpt_llm = LLMFactory.get_llm("GPT", MOCK_GPT_KEY)
    print(gpt_llm.generate_response("What is the return policy for electronics?"))
    print(gpt_llm.generate_response("Product information: Smartwatch X200 features?"))

    print("\n--- Using Gemini LLM ---")
    gemini_llm = LLMFactory.get_llm("Gemini", MOCK_GEMINI_KEY)
    print(gemini_llm.generate_response("How do I change my shipping address for order #G54321?"))
    print(gemini_llm.generate_response("Product information: What are the benefits of organic coffee?"))

    print("\n--- Using Llama LLM ---")
    llama_llm = LLMFactory.get_llm("Llama", MOCK_LLAMA_KEY)
    print(llama_llm.generate_response("Where is my package with tracking number TRK987654?"))
    print(llama_llm.generate_response("Product information: How to care for a silk shirt?"))

    print("\n--- Attempting unsupported LLM ---")
    try:
        unsupported_llm = LLMFactory.get_llm("UnsupportedLLM", "mock-key")
    except ValueError as e:
        print(f"Error: {e}")