from abc import ABC, abstractmethod
from typing import Dict, Any

class AbstractLLM(ABC):
    """
    Abstract base class for all LLM providers.
    Defines the common interface for generating product descriptions.
    """
    @abstractmethod
    def generate_description(self, product_details: Dict[str, Any]) -> str:
        """
        Generates a product description based on the given product details.
        """
        pass

class OpenAILLM(AbstractLLM):
    """
    Concrete implementation for OpenAI's LLM.
    """
    def __init__(self, api_key: str):
        self.api_key = api_key
        # In a real application, you would initialize the OpenAI client here
        print(f"Initializing OpenAI LLM with API Key: {'*' * (len(api_key) - 4)}{api_key[-4:]}")

    def generate_description(self, product_details: Dict[str, Any]) -> str:
        # Simulate API call to OpenAI
        product_name = product_details.get("name", "")
        features = ", ".join(product_details.get("features", []))
        prompt = f"Generate a compelling e-commerce product description for '{product_name}' with key features: {features}."
        print(f"[OpenAI LLM] Simulating generation for: {product_name}")
        # In a real scenario, this would involve an actual API call:
        # response = openai.Completion.create(engine="text-davinci-003", prompt=prompt, max_tokens=150)
        # return response.choices[0].text.strip()
        return f"[Generated by OpenAI] Discover the {product_name}! Featuring {features}, it's designed to elevate your experience. This premium product offers unparalleled quality and innovation."

class GeminiLLM(AbstractLLM):
    """
    Concrete implementation for Google Gemini's LLM.
    """
    def __init__(self, api_key: str):
        self.api_key = api_key
        # In a real application, you would initialize the Gemini client here
        print(f"Initializing Gemini LLM with API Key: {'*' * (len(api_key) - 4)}{api_key[-4:]}")

    def generate_description(self, product_details: Dict[str, Any]) -> str:
        # Simulate API call to Gemini
        product_name = product_details.get("name", "")
        features = ", ".join(product_details.get("features", []))
        prompt = f"Craft an engaging e-commerce description for the product '{product_name}'. Highlight these features: {features}."
        print(f"[Gemini LLM] Simulating generation for: {product_name}")
        # In a real scenario, this would involve an actual API call:
        # response = gemini.generate_text(model="models/text-bison-001", prompt=prompt)
        # return response.result.strip()
        return f"[Generated by Gemini] Introducing the {product_name}, a must-have item that boasts {features}. Experience superior performance and thoughtful design with this exceptional product."

class LlamaSimulatedLLM(AbstractLLM):
    """
    Simulated concrete implementation for a Llama-like LLM (for demonstration).
    """
    def __init__(self, model_path: str = "./llama_model_weights"):
        self.model_path = model_path
        # In a real application, you might load a local Llama model or connect to a serving endpoint
        print(f"Initializing Llama-like LLM from path: {model_path}")

    def generate_description(self, product_details: Dict[str, Any]) -> str:
        # Simulate local model inference for Llama
        product_name = product_details.get("name", "")
        features = ", ".join(product_details.get("features", []))
        prompt = f"Write a concise e-commerce description for '{product_name}'. Key attributes: {features}."
        print(f"[Llama LLM] Simulating generation for: {product_name}")
        # In a real scenario, this would involve local model inference:
        # model = load_llama_model(self.model_path)
        # output = model.generate(prompt)
        # return output.strip()
        return f"[Generated by Llama (Simulated)] Get the {product_name}! With {features}, it delivers robust functionality and an intuitive user experience. Perfect for your needs."
