import abc
import os

# --- 1. Configuration (`config.py` concept) ---
class Config:
    ACTIVE_LLM = os.environ.get("ACTIVE_LLM", "openai").lower() # Default to openai
    OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY", "sk-mock-openai-key")
    GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY", "mock-gemini-key")
    LLAMA_API_KEY = os.environ.get("LLAMA_API_KEY", "mock-llama-key")


# --- 2. LLM Abstraction Layer (`llm_interface.py`) ---
class LLMProvider(abc.ABC):
    @abc.abstractmethod
    def generate_description(self, product_details: dict) -> str:
        pass


# --- 3. Concrete LLM Implementations (`openai_llm.py`, `gemini_llm.py`, `llama_llm.py`) ---
class OpenAILLM(LLMProvider):
    def __init__(self):
        # In a real scenario, initialize OpenAI client with Config.OPENAI_API_KEY
        pass

    def generate_description(self, product_details: dict) -> str:
        product_name = product_details.get("name", "product")
        features = ", ".join(product_details.get("features", []))
        # Simulate API call and response parsing
        return f"[Generated by OpenAI GPT] Discover the {product_name} with features like {features}. Experience unparalleled quality."


class GeminiLLM(LLMProvider):
    def __init__(self):
        # In a real scenario, initialize Gemini client with Config.GEMINI_API_KEY
        pass

    def generate_description(self, product_details: dict) -> str:
        product_name = product_details.get("name", "product")
        category = product_details.get("category", "item")
        # Simulate API call and response parsing
        return f"[Generated by Google Gemini] Elevate your experience with this {category}, the {product_name}. Smart, efficient, and innovative."


class LlamaLLM(LLMProvider):
    def __init__(self):
        # In a real scenario, initialize Llama client with Config.LLAMA_API_KEY
        pass

    def generate_description(self, product_details: dict) -> str:
        product_name = product_details.get("name", "product")
        material = product_details.get("material", "high-quality material")
        # Simulate API call and response parsing
        return f"[Generated by Meta Llama] Introducing the exquisite {product_name}, crafted from {material}. Designed for durability and style."


# --- 4. LLM Factory/Manager (`llm_factory.py`) ---
class LLMFactory:
    _providers = {}

    @classmethod
    def register_provider(cls, name: str, provider_class):
        if not issubclass(provider_class, LLMProvider):
            raise ValueError("Provider class must inherit from LLMProvider")
        cls._providers[name.lower()] = provider_class

    @classmethod
    def get_provider(cls, name: str) -> LLMProvider:
        provider_class = cls._providers.get(name.lower())
        if not provider_class:
            raise ValueError(f"No LLM provider registered with name: {name}")
        return provider_class()


# --- 5. Product Description Generator Application Logic (`product_description_generator.py`) ---
class ProductDescriptionGenerator:
    def __init__(self, llm_provider: LLMProvider):
        self._llm_provider = llm_provider

    def generate_product_description(self, product_details: dict) -> str:
        if not isinstance(product_details, dict):
            raise ValueError("product_details must be a dictionary")
        return self._llm_provider.generate_description(product_details)


# --- 6. Main Application (`main.py`) ---
if __name__ == "__main__":
    # Register available LLM providers
    LLMFactory.register_provider("openai", OpenAILLM)
    LLMFactory.register_provider("gemini", GeminiLLM)
    LLMFactory.register_provider("llama", LlamaLLM)

    # Example Product Details
    product_data_1 = {
        "name": "Smartwatch X",
        "category": "Electronics",
        "features": ["GPS", "Heart Rate Monitor", "Waterproof", "Long Battery Life"]
    }

    product_data_2 = {
        "name": "Vintage Leather Jacket",
        "category": "Apparel",
        "material": "genuine leather",
        "features": ["Stylish Design", "Comfort Fit", "Durable"]
    }

    print(f"--- Initial Configuration: Active LLM = {Config.ACTIVE_LLM.upper()} ---")
    try:
        # Get the configured LLM provider
        active_llm_provider = LLMFactory.get_provider(Config.ACTIVE_LLM)
        generator = ProductDescriptionGenerator(active_llm_provider)

        # Generate description for product 1
        description_1 = generator.generate_product_description(product_data_1)
        print(f"\nProduct: {product_data_1['name']}")
        print(f"Description: {description_1}")

        # Generate description for product 2
        description_2 = generator.generate_product_description(product_data_2)
        print(f"\nProduct: {product_data_2['name']}")
        print(f"Description: {description_2}")

    except ValueError as e:
        print(f"Error: {e}")

    print("\n--- Demonstrating LLM Switching (e.g., changing ACTIVE_LLM environment variable) ---")
    # Simulate changing the active LLM by directly modifying Config.ACTIVE_LLM for demonstration
    # In a real app, this would be done via environment variable, config file reload, or dynamic API call.

    # Switch to Gemini
    Config.ACTIVE_LLM = "gemini"
    print(f"\nSwitching to Active LLM = {Config.ACTIVE_LLM.upper()}")
    try:
        active_llm_provider = LLMFactory.get_provider(Config.ACTIVE_LLM)
        generator = ProductDescriptionGenerator(active_llm_provider)
        description_1_gemini = generator.generate_product_description(product_data_1)
        print(f"Product: {product_data_1['name']}")
        print(f"Description: {description_1_gemini}")
    except ValueError as e:
        print(f"Error: {e}")

    # Switch to Llama
    Config.ACTIVE_LLM = "llama"
    print(f"\nSwitching to Active LLM = {Config.ACTIVE_LLM.upper()}")
    try:
        active_llm_provider = LLMFactory.get_provider(Config.ACTIVE_LLM)
        generator = ProductDescriptionGenerator(active_llm_provider)
        description_2_llama = generator.generate_product_description(product_data_2)
        print(f"Product: {product_data_2['name']}")
        print(f"Description: {description_2_llama}")
    except ValueError as e:
        print(f"Error: {e}")

    # Test with an unregistered provider
    Config.ACTIVE_LLM = "unregistered_llm"
    print(f"\nAttempting to use an unregistered LLM = {Config.ACTIVE_LLM.upper()}")
    try:
        active_llm_provider = LLMFactory.get_provider(Config.ACTIVE_LLM)
        generator = ProductDescriptionGenerator(active_llm_provider)
        description_error = generator.generate_product_description(product_data_1)
        print(f"Product: {product_data_1['name']}")
        print(f"Description: {description_error}")
    except ValueError as e:
        print(f"Caught expected error: {e}")