from abc import ABC, abstractmethod

# 1. Configuration Management
class Config:
    ACTIVE_LLM_PROVIDER = "GEMINI"  # Can be "GPT", "GEMINI", "LLAMA"
    # Simulated API keys
    GPT_API_KEY = "sk-mock_gpt_key"
    GEMINI_API_KEY = "mock_gemini_key"
    LLAMA_API_KEY = "hf_mock_llama_key"


# 2. LLM Interface (Abstraction Layer)
class LLMInterface(ABC):
    @abstractmethod
    def generate_response(self, prompt: str) -> str:
        pass


# 3. Concrete LLM Providers
class GPTProvider(LLMInterface):
    def __init__(self, api_key: str):
        self.api_key = api_key

    def generate_response(self, prompt: str) -> str:
        # Simulate GPT API call
        print(f"[GPTProvider] Using API Key: {self.api_key[:5]}...")
        formatted_prompt = f"GPT-specific format: {prompt}"
        response = f"GPT says: {formatted_prompt.upper()} (processed by GPT)"
        return response


class GeminiProvider(LLMInterface):
    def __init__(self, api_key: str):
        self.api_key = api_key

    def generate_response(self, prompt: str) -> str:
        # Simulate Gemini API call
        print(f"[GeminiProvider] Using API Key: {self.api_key[:5]}...")
        formatted_prompt = f"Gemini-specific format: {prompt}"
        response = f"Gemini says: {formatted_prompt.capitalize()} (powered by Gemini)"
        return response


class LlamaProvider(LLMInterface):
    def __init__(self, api_key: str):
        self.api_key = api_key

    def generate_response(self, prompt: str) -> str:
        # Simulate Llama API call
        print(f"[LlamaProvider] Using API Key: {self.api_key[:5]}...")
        formatted_prompt = f"Llama-specific format: {prompt}"
        response = f"Llama says: {formatted_prompt} (generated by Llama)"
        return response


# 4. LLM Factory (Dynamic Selection)
class LLMFactory:
    @staticmethod
    def get_llm_provider(provider_name: str) -> LLMInterface:
        if provider_name == "GPT":
            return GPTProvider(Config.GPT_API_KEY)
        elif provider_name == "GEMINI":
            return GeminiProvider(Config.GEMINI_API_KEY)
        elif provider_name == "LLAMA":
            return LlamaProvider(Config.LLAMA_API_KEY)
        else:
            raise ValueError(f"Unknown LLM provider: {provider_name}")


# 5. Chatbot Core Logic
class CustomerSupportChatbot:
    def __init__(self, llm_provider: LLMInterface):
        self.llm_provider = llm_provider

    def chat(self, user_query: str) -> str:
        print(f"\nUser: {user_query}")
        response = self.llm_provider.generate_response(user_query)
        print(f"Chatbot: {response}")
        return response


# Example Usage
if __name__ == "__main__":
    print(f"--- Initializing Chatbot with {Config.ACTIVE_LLM_PROVIDER} Provider ---")
    try:
        # Get LLM provider dynamically from config
        selected_llm_provider = LLMFactory.get_llm_provider(Config.ACTIVE_LLM_PROVIDER)
        chatbot = CustomerSupportChatbot(selected_llm_provider)

        chatbot.chat("I have a problem with my order #12345.")
        chatbot.chat("How do I reset my password?")

        # Demonstrate switching providers by changing config and re-initializing
        print("\n--- Switching to GPT Provider ---")
        Config.ACTIVE_LLM_PROVIDER = "GPT"
        selected_llm_provider = LLMFactory.get_llm_provider(Config.ACTIVE_LLM_PROVIDER)
        chatbot_gpt = CustomerSupportChatbot(selected_llm_provider)
        chatbot_gpt.chat("What is your return policy?")

        print("\n--- Switching to Llama Provider ---")
        Config.ACTIVE_LLM_PROVIDER = "LLAMA"
        selected_llm_provider = LLMFactory.get_llm_provider(Config.ACTIVE_LLM_PROVIDER)
        chatbot_llama = CustomerSupportChatbot(selected_llm_provider)
        chatbot_llama.chat("Tell me about your premium features.")

    except ValueError as e:
        print(f"Error: {e}")