import gradio as gr

# --- LLM Simulation (Replace with actual LLM integration) ---
def generate_analogous_problem(problem: str) -> str:
    if "math" in problem.lower():
        # Simple placeholder for math problem analogy
        if "solve for x" in problem.lower():
            return "Let\'s try an analogous problem: Solve for y in the equation 3y - 9 = 15."
        else:
            return "Let\'s try a similar math concept: Explain the steps to find the area of a circle given its radius."
    elif "code" in problem.lower() or "programming" in problem.lower():
        # Simple placeholder for coding problem analogy
        if "reverse string" in problem.lower():
            return "Consider this coding challenge: Write a Python function to check if a string is a palindrome."
        else:
            return "Consider this coding challenge: Write a function to find the largest number in a list."
    else:
        return f"Here\'s an analogous problem to \"{problem}\": [Analogous problem generated by LLM]"

def generate_cot_solution(analogous_problem: str) -> str:
    if "3y - 9 = 15" in analogous_problem:
        return (
            "Step-by-step solution for 3y - 9 = 15:\n"
            "1. Add 9 to both sides: 3y - 9 + 9 = 15 + 9 => 3y = 24\n"
            "2. Divide both sides by 3: 3y / 3 = 24 / 3 => y = 8\n"
            "So, y = 8."
        )
    elif "area of a circle" in analogous_problem:
        return (
            "Chain-of-Thought for area of a circle:\n"
            "1. Understand the formula: The area (A) of a circle is given by A = πr², where r is the radius.\n"
            "2. Identify the given: You are given the radius (r).\n"
            "3. Apply the formula: Substitute the value of r into the formula A = πr² to calculate the area."
        )
    elif "palindrome" in analogous_problem:
        return (
            "CoT for palindrome check (Python):\n"
            "1. Define a function that takes a string as input.\n"
            "2. Convert the string to lowercase to handle case insensitivity.\n"
            "3. Reverse the string. In Python, this can be done using slicing `s[::-1]` or `reversed()` and `join()`.\n"
            "4. Compare the original (lowercase) string with the reversed string. If they are the same, it\'s a palindrome.\n"
            "```python\n"
            "def is_palindrome(s):\n"
            "    s = s.lower()\n"
            "    return s == s[::-1]\n"
            "```"
        )
    elif "largest number in a list" in analogous_problem:
        return (
            "CoT for finding largest number in a list (Python):\n"
            "1. Define a function that takes a list of numbers as input.\n"
            "2. Handle edge cases: If the list is empty, return an appropriate value (e.g., None or raise an error).\n"
            "3. Initialize a variable (e.g., `max_num`) with the first element of the list.\n"
            "4. Iterate through the rest of the list. For each number, compare it with `max_num`. If the current number is greater, update `max_num`.\n"
            "5. After iterating through the entire list, `max_num` will hold the largest number.\n"
            "```python\n"
            "def find_largest_number(numbers):\n"
            "    if not numbers:\n"
            "        return None # Or raise an error\n"
            "    max_num = numbers[0]\n"
            "    for num in numbers:\n"
            "        if num > max_num:\n"
            "            max_num = num\n"
            "    return max_num\n"
            "```"
        )
    else:
        return f"Detailed Chain-of-Thought for \"{analogous_problem}\": [CoT solution generated by LLM]"

# --- Gradio Interface Logic ---
def tutor_logic(student_problem: str) -> tuple[str, str]:
    # Step 1: Generate an analogous problem
    analogous_problem = generate_analogous_problem(student_problem)
    
    # Step 2: Generate Chain-of-Thought solution for the analogous problem
    cot_solution = generate_cot_solution(analogous_problem)
    
    return analogous_problem, cot_solution

# --- Gradio Interface Definition ---
iface = gr.Interface(
    fn=tutor_logic,
    inputs=gr.Textbox(lines=2, placeholder="Enter your math or coding problem here..."),
    outputs=[
        gr.Textbox(label="Analogous Problem"),
        gr.Textbox(label="Chain-of-Thought Solution", lines=10),
    ],
    title="AI Math & Coding Tutor (Analogical Prompting Demo)",
    description="Enter a math problem or a coding challenge, and I will generate an analogous problem with a step-by-step Chain-of-Thought solution to help you understand the concept."
)

if __name__ == "__main__":
    iface.launch()