import itertools

class MockLLMClient:
    def generate_text(self, prompt: str) -> str:
        if "list key attributes for" in prompt.lower():
            if "clothing" in prompt.lower():
                return "material, color, season, occasion"
            elif "electronics" in prompt.lower():
                return "brand, model, feature, capacity"
            else:
                return "attribute1, attribute2"
        elif "provide diverse example values for" in prompt.lower():
            if "material" in prompt.lower() and "clothing" in prompt.lower():
                return "cotton, silk, polyester, wool"
            elif "color" in prompt.lower() and "clothing" in prompt.lower():
                return "blue, red, green, black"
            elif "season" in prompt.lower() and "clothing" in prompt.lower():
                return "summer, winter, spring, autumn"
            elif "occasion" in prompt.lower() and "clothing" in prompt.lower():
                return "casual, formal, sports, party"
            elif "brand" in prompt.lower() and "electronics" in prompt.lower():
                return "Samsung, Apple, Sony, LG"
            elif "model" in prompt.lower() and "electronics" in prompt.lower():
                return "Galaxy S23, iPhone 15, Bravia X1, OLED C2"
            else:
                return "value1, value2, value3"
        else:
            # Simulate product description generation
            category_part = ""
            if "category:" in prompt.lower():
                category_start = prompt.lower().find("category:") + len("category:")
                category_end = prompt.lower().find("\n", category_start)
                if category_end == -1: category_end = len(prompt)
                category_part = prompt[category_start:category_end].strip()

            attributes_part = ""
            if "attributes:" in prompt.lower():
                attributes_start = prompt.lower().find("attributes:") + len("attributes:")
                attributes_part = prompt[attributes_start:].strip()

            if category_part and attributes_part:
                return f"Introducing a fantastic {category_part} with {attributes_part}. Designed for your ultimate satisfaction."
            else:
                return "A default product description generated by the LLM."


class ProductDescriptionGenerator:
    def __init__(self, llm_client):
        self.llm_client = llm_client

    def _get_attributes_for_category(self, category: str) -> list[str]:
        prompt = f"List key attributes for the product category: {category}. Provide them as a comma-separated list."
        response = self.llm_client.generate_text(prompt)
        return [attr.strip() for attr in response.split(',') if attr.strip()]

    def _get_attribute_values_for_attribute(self, attribute: str, category: str) -> list[str]:
        prompt = f"Provide diverse example values for the attribute '{attribute}' within the product category '{category}'. Provide them as a comma-separated list."
        response = self.llm_client.generate_text(prompt)
        return [value.strip() for value in response.split(',') if value.strip()]

    def generate_description(self, category: str, attributes_with_values: dict) -> str:
        attr_string = ", ".join([f"{k}: {v}" for k, v in attributes_with_values.items()])
        prompt = f"Generate a product description for the category: {category}\nAttributes: {attr_string}"
        return self.llm_client.generate_text(prompt)

    def generate_diverse_descriptions(self, category: str, num_descriptions=3) -> list[dict]:
        attributes = self._get_attributes_for_category(category)
        if not attributes:
            return []

        all_attribute_values = {}
        for attr in attributes:
            all_attribute_values[attr] = self._get_attribute_values_for_attribute(attr, category)

        if not all_attribute_values or all(not values for values in all_attribute_values.values()):
            return []

        # Generate combinations for diversity
        # Create a list of lists of attribute values, aligning with the order of `attributes`
        attribute_value_lists = [all_attribute_values[attr] for attr in attributes]

        # Use itertools.product to get all possible combinations
        all_combinations = list(itertools.product(*attribute_value_lists))

        # Select up to num_descriptions combinations, ensuring some diversity
        selected_combinations_raw = []
        if len(all_combinations) <= num_descriptions:
            selected_combinations_raw = all_combinations
        else:
            # Simple strategy: pick evenly spaced combinations for diversity
            step = len(all_combinations) // num_descriptions if num_descriptions > 0 else 1
            for i in range(num_descriptions):
                selected_combinations_raw.append(all_combinations[i * step % len(all_combinations)])

        diverse_descriptions = []
        for combo in selected_combinations_raw:
            attributes_for_description = {}
            for i, attr_name in enumerate(attributes):
                attributes_for_description[attr_name] = combo[i]
            
            description = self.generate_description(category, attributes_for_description)
            diverse_descriptions.append({
                "description": description,
                "attributes_used": attributes_for_description
            })
        
        return diverse_descriptions


if __name__ == "__main__":
    llm_client = MockLLMClient()
    generator = ProductDescriptionGenerator(llm_client)

    print("Generating diverse descriptions for 'clothing':")
    clothing_descriptions = generator.generate_diverse_descriptions("clothing", num_descriptions=4)
    for i, desc_data in enumerate(clothing_descriptions):
        print(f"\nDescription {i+1}:")
        print(f"  Attributes: {desc_data['attributes_used']}")
        print(f"  Text: {desc_data['description']}")

    print("\n" + "-"*50 + "\n")

    print("Generating diverse descriptions for 'electronics':")
    electronics_descriptions = generator.generate_diverse_descriptions("electronics", num_descriptions=2)
    for i, desc_data in enumerate(electronics_descriptions):
        print(f"\nDescription {i+1}:")
        print(f"  Attributes: {desc_data['attributes_used']}")
        print(f"  Text: {desc_data['description']}")