import re

class MockInternalTool:
    def reset_password(self, user_id):
        return f"Simulating password reset for {user_id}. A reset link has been sent."

    def update_subscription(self, user_id, plan):
        return f"Simulating subscription update for {user_id} to {plan} plan."

    def fetch_user_data(self, user_id, data_type):
        if data_type == "subscription_status":
            return f"Simulating fetching subscription status for {user_id}: Currently on Basic plan."
        elif data_type == "account_details":
            return f"Simulating fetching account details for {user_id}: Email: user@example.com, Joined: Jan 2023."
        return f"Simulating fetching {data_type} for {user_id}."

class BehaviorCloningPolicy:
    def __init__(self, demonstrations):
        self.demonstrations = demonstrations
        self.intent_map = {}
        self._train()

    def _train(self):
        for demo in self.demonstrations:
            query = demo["customer_query"].lower()
            command = demo["internal_tool_command"]

            if "reset password" in query or "forgot password" in query or "password isn't working" in query:
                self.intent_map["reset_password"] = command
            elif "update subscription" in query or "change plan" in query or "upgrade my plan" in query:
                if "plan='premium'" in command:
                    self.intent_map["update_subscription_premium"] = command
                else:
                    self.intent_map["update_subscription_generic"] = command
            elif "subscription status" in query or "my current subscription" in query:
                self.intent_map["fetch_subscription_status"] = command
            elif "account details" in query or "check my account" in query:
                self.intent_map["fetch_account_details"] = command

    def predict_action(self, customer_query):
        query = customer_query.lower()

        if "reset password" in query or "forgot password" in query or "password isn't working" in query:
            return self.intent_map.get("reset_password", "Unknown command.")
        
        if "premium" in query and ("update subscription" in query or "change plan" in query or "upgrade my plan" in query):
            return self.intent_map.get("update_subscription_premium", "Unknown command.")
        elif "update subscription" in query or "change plan" in query or "upgrade my plan" in query:
            return self.intent_map.get("update_subscription_generic", "Unknown command.")

        if "subscription status" in query or "my current subscription" in query:
            return self.intent_map.get("fetch_subscription_status", "Unknown command.")
        elif "account details" in query or "check my account" in query:
            return self.intent_map.get("fetch_account_details", "Unknown command.")
        
        return "Unknown command."


class CustomerSupportChatbot:
    def __init__(self, policy, internal_tool):
        self.policy = policy
        self.internal_tool = internal_tool

    def handle_query(self, customer_query):
        predicted_command_string = self.policy.predict_action(customer_query)

        if predicted_command_string == "Unknown command.":
            return "I'm sorry, I don't understand that request. Can you please rephrase it?"

        match = re.match(r"(\w+)\\((.*)\\)", predicted_command_string)
        if not match:
            return "Error: Invalid command format generated by policy."

        method_name = match.group(1)
        args_string = match.group(2)

        method = getattr(self.internal_tool, method_name, None)
        if not method:
            return f"Error: Internal tool does not have a method '{method_name}'."

        args = {}
        arg_pairs = args_string.split(',')
        for arg_pair in arg_pairs:
            arg_pair = arg_pair.strip()
            if '=' in arg_pair:
                key, value_raw = arg_pair.split('=', 1)
                value = value_raw.strip().strip("'\"")
                args[key.strip()] = value

        try:
            tool_response = method(**args)
            action_description = method_name.replace('_', ' ')
            return f"Okay, I've performed the action: '{action_description}'. Here's the result: {tool_response}"
        except TypeError as e:
            return f"Error executing internal tool command: The arguments provided did not match the expected parameters for '{method_name}'. Details: {e}"
        except Exception as e:
            return f"An unexpected error occurred while processing your request: {e}"


if __name__ == "__main__":
    demonstrations = [
        {"customer_query": "I forgot my password, can you help me reset it?", "internal_tool_command": "reset_password(user_id='customer_123')"},
        {"customer_query": "I want to change my subscription plan to premium.", "internal_tool_command": "update_subscription(user_id='customer_123', plan='premium')"},
        {"customer_query": "What is my current subscription status?", "internal_tool_command": "fetch_user_data(user_id='customer_123', data_type='subscription_status')"},
        {"customer_query": "Can you check my account details?", "internal_tool_command": "fetch_user_data(user_id='customer_123', data_type='account_details')"},
        {"customer_query": "My password isn't working.", "internal_tool_command": "reset_password(user_id='customer_123')"},
        {"customer_query": "Upgrade my plan please.", "internal_tool_command": "update_subscription(user_id='customer_123', plan='premium')"},
        {"customer_query": "Show me my subscription.", "internal_tool_command": "fetch_user_data(user_id='customer_123', data_type='subscription_status')"},
    ]

    mock_tool = MockInternalTool()
    policy = BehaviorCloningPolicy(demonstrations)
    chatbot = CustomerSupportChatbot(policy, mock_tool)

    print("--- Chatbot Demonstration ---")
    queries = [
        "I forgot my password.",
        "Upgrade my plan to premium.",
        "What's my subscription status?",
        "Can you reset my password please?",
        "Change my plan to basic.", 
        "Tell me a joke.",
        "Show my account details."
    ]

    for query in queries:
        print(f"\nCustomer: {query}")
        response = chatbot.handle_query(query)
        print(f"Chatbot: {response}")