import torch
from transformers import BartForConditionalGeneration, BartTokenizer
from sentence_transformers import SentenceTransformer
import faiss
import numpy as np

class Retriever:
    def __init__(self, model_name="sentence-transformers/all-MiniLM-L6-v2", device="cpu"):
        self.device = device
        self.model = SentenceTransformer(model_name).to(self.device)
        self.index = None
        self.documents = []
        print(f"Retriever initialized with model: {model_name} on device: {self.device}")

    def _embed_texts(self, texts):
        embeddings = self.model.encode(texts, convert_to_tensor=True, show_progress_bar=False)
        return embeddings.cpu().numpy()

    def build_index(self, documents):
        self.documents = documents
        if not documents:
            print("No documents provided to build index.")
            return
        print(f"Building index for {len(documents)} documents...")
        document_embeddings = self._embed_texts(documents)
        self.index = faiss.IndexFlatL2(document_embeddings.shape[1])
        self.index.add(document_embeddings)
        print("FAISS index built successfully.")

    def retrieve(self, query, top_k=5):
        if self.index is None:
            print("Index not built. Cannot retrieve documents.")
            return []
        
        query_embedding = self._embed_texts([query])
        distances, indices = self.index.search(query_embedding, top_k)
        
        retrieved_docs = []
        for i in indices[0]:
            if 0 <= i < len(self.documents):
                retrieved_docs.append(self.documents[i])
        print(f"Retrieved {len(retrieved_docs)} documents for query.")
        return retrieved_docs

class Generator:
    def __init__(self, model_name="facebook/bart-base", device="cpu"):
        self.device = device
        self.tokenizer = BartTokenizer.from_pretrained(model_name)
        self.model = BartForConditionalGeneration.from_pretrained(model_name).to(self.device)
        print(f"Generator initialized with model: {model_name} on device: {self.device}")

    def generate_response(self, query, contexts, max_length=200, num_beams=4):
        # Concatenate contexts and query for the prompt
        if contexts:
            context_str = " ".join(contexts)
            prompt = f"Based on the following medical information: {context_str}. Answer the query: {query}"
        else:
            prompt = f"Answer the query: {query}"
            print("No contexts provided to the generator. Generating response based on query only.")

        inputs = self.tokenizer(prompt, return_tensors="pt", max_length=1024, truncation=True).to(self.device)
        
        # Generate response
        with torch.no_grad():
            output_sequences = self.model.generate(
                inputs["input_ids"],
                attention_mask=inputs["attention_mask"],
                max_length=max_length,
                num_beams=num_beams,
                early_stopping=True
            )
        
        response = self.tokenizer.decode(output_sequences[0], skip_special_tokens=True)
        print("Response generated by generator.")
        return response

class RAGSystem:
    def __init__(self, retriever_model="sentence-transformers/all-MiniLM-L6-v2", generator_model="facebook/bart-base", device="cpu"):
        self.retriever = Retriever(model_name=retriever_model, device=device)
        self.generator = Generator(model_name=generator_model, device=device)
        print("RAGSystem initialized.")

    def ingest_documents(self, documents):
        self.retriever.build_index(documents)

    def query(self, patient_query, top_k=5):
        print(f"Processing query: '{patient_query}' with top_k={top_k}")
        retrieved_contexts = self.retriever.retrieve(patient_query, top_k=top_k)
        
        # Formulate a structured output, including sources if available
        if retrieved_contexts:
            generated_text = self.generator.generate_response(patient_query, retrieved_contexts)
            sources = [f"Source {i+1}: {doc[:100]}..." for i, doc in enumerate(retrieved_contexts)] # Truncate for display
            full_response = f"Diagnosis/Recommendation: {generated_text}\n\nRelevant Medical Contexts:\n" + "\n".join(sources)
        else:
            # If no contexts are retrieved, still try to generate a response, but warn the user
            generated_text = self.generator.generate_response(patient_query, [])
            full_response = f"Diagnosis/Recommendation (Note: No specific medical contexts retrieved): {generated_text}\n\n"\
                            f"Consider refining your query for better context retrieval."
        
        return full_response

