from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain_community.vectorstores import Chroma
from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_community.llms import Ollama # Requires Ollama server to be running and model pulled (e.g., 'ollama pull llama2')
from langchain.chains import RetrievalQA
import os

class MedicalDiagnosticAssistant:
    def __init__(self, persist_directory: str = "./chroma_db"):
        self.persist_directory = persist_directory
        # Initialize the embedding model
        self.embedding_model = HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2")
        
        # Initialize ChromaDB
        # If the directory exists, it will load the existing collection
        self.vectorstore = Chroma(
            collection_name="medical_literature",
            embedding_function=self.embedding_model,
            persist_directory=self.persist_directory
        )
        
        # Initialize the Large Language Model (LLM)
        # This assumes Ollama server is running locally and 'llama2' model is available.
        # For other LLMs (e.g., OpenAI, HuggingFace local models), adjust this part.
        try:
            self.llm = Ollama(model="llama2")
        except Exception as e:
            print(f"Warning: Could not initialize Ollama LLM. Please ensure Ollama server is running and 'llama2' model is pulled. Error: {e}")
            print("Using a placeholder for LLM. Responses will not be generated by a real LLM.")
            self.llm = None # Placeholder if Ollama isn't available

        # Setup the Retrieval-Augmented Generation (RAG) chain
        self.qa_chain = None
        if self.llm:
            self.qa_chain = RetrievalQA.from_chain_type(
                llm=self.llm,
                chain_type="stuff", # "stuff" combines all retrieved documents into one prompt
                retriever=self.vectorstore.as_retriever(search_kwargs={"k": 3}), # Retrieve top 3 similar documents
                return_source_documents=True
            )
        else:
            print("QA chain not initialized due to LLM unavailability.")

    def ingest_medical_data(self, documents: list[str]):
        text_splitter = RecursiveCharacterTextSplitter(
            chunk_size=1000,
            chunk_overlap=200,
            length_function=len,
            add_start_index=True,
        )
        
        texts = text_splitter.create_documents(documents)
        print(f"Ingesting {len(texts)} document chunks into ChromaDB...")
        
        # Add texts and their embeddings to the vector store
        self.vectorstore.add_documents(texts)
        self.vectorstore.persist() # Save changes to disk
        print("Medical data ingestion complete and persisted.")

    def answer_query(self, query: str) -> dict:
        if not self.qa_chain:
            print("Cannot answer query: LLM or QA chain not initialized.")
            # Fallback: perform just retrieval if LLM isn't available
            retrieved_docs = self.vectorstore.similarity_search(query, k=3)
            return {
                "query": query,
                "result": "LLM not available to generate a full answer. Retrieved documents below:",
                "source_documents": retrieved_docs
            }

        print(f"Processing query: '{query}'")
        response = self.qa_chain({"query": query})
        return response

# Example Usage:
if __name__ == "__main__":
    # Clear previous ChromaDB for a fresh start (optional)
    if os.path.exists("./chroma_db"):
        import shutil
        shutil.rmtree("./chroma_db")
        print("Cleaned up existing ChromaDB directory.")

    assistant = MedicalDiagnosticAssistant()

    # Simulate some medical literature
    medical_docs = [
        "COVID-19 symptoms often include fever, cough, fatigue, and loss of taste or smell. Severe cases can lead to pneumonia and acute respiratory distress syndrome.",
        "Diabetes Mellitus Type 2 is characterized by insulin resistance and relative insulin deficiency. Management involves diet, exercise, and often medication like metformin.",
        "Hypertension, or high blood pressure, increases the risk of heart disease and stroke. Lifestyle modifications and antihypertensive drugs are common treatments.",
        "A common cold is a viral infectious disease of the upper respiratory tract that primarily affects the nose, throat, sinuses, and larynx. Symptoms include coughing, sore throat, runny nose, and fever.",
        "Influenza is a contagious respiratory illness caused by influenza viruses. It can cause mild to severe illness, and at times can lead to death. Symptoms are more severe than a common cold."
    ]

    # Ingest the simulated data
    assistant.ingest_medical_data(medical_docs)

    # Ask some diagnostic questions
    queries = [
        "What are the typical symptoms of COVID-19?",
        "How is Type 2 Diabetes usually managed?",
        "Symptoms of a common cold vs. flu."
    ]

    for q in queries:
        print("\n" + "="*50 + "\n")
        response = assistant.answer_query(q)
        print(f"Query: {response['query']}")
        print(f"Answer: {response['result']}")
        print("\nSource Documents:")
        for i, doc in enumerate(response.get('source_documents', [])):
            print(f"  [{i+1}] {doc.page_content[:200]}...") # Print first 200 chars
        if not response.get('source_documents'):
            print("  No source documents retrieved (LLM not initialized or retrieval failed).")
