
import pandas as pd
import spacy
from pydantic import BaseModel, Field
from typing import List, Dict, Optional, Any

# LangGraph / LangChain imports (mocking actual LLM and graph for a single file)
# In a real scenario, you'd import from langchain_core.messages, langchain_core.runnables, etc.
# and use a concrete LLM implementation like ChatOpenAI.


# --- 1. Data Models (Pydantic) ---
class PatientData(BaseModel):
    patient_id: str
    age: int
    gender: str
    diagnoses: List[str]
    medications: List[str]
    allergies: List[str] = []
    lab_results: Dict[str, Any] = {}
    notes: Optional[str] = None

class MedicalGuideline(BaseModel):
    guideline_id: str
    disease: str
    recommendations: List[str]
    contraindications: List[str] = []
    dosage_info: Dict[str, str] = {}

class TreatmentPlanStep(BaseModel):
    step_id: str
    description: str
    action_type: str  # e.g., 'medication_adjustment', 'lifestyle_change', 'monitoring'
    details: Dict[str, Any] = {}
    dependencies: List[str] = [] # Other step_ids this step depends on

class TreatmentPlan(BaseModel):
    plan_id: str
    patient_id: str
    goal: str
    steps: List[TreatmentPlanStep]
    status: str = "draft"
    version: int = 1

# --- 2. Data Ingestion & Preprocessing Module (Mock) ---
class DataProcessor:
    def __init__(self):
        # For demonstration, we'll use a simple mock for spaCy functionality
        # In a real application, you'd load a model: self.nlp = spacy.load("en_core_web_sm")
        pass

    def process_patient_data(self, raw_data: Dict) -> PatientData:
        # Simulate parsing raw data into PatientData Pydantic model
        try:
            patient = PatientData(**raw_data)
            if patient.notes:
                # Simple mock NLP to extract potential entities from notes
                print(f"[DataProcessor] Simulating NLP for patient notes: {patient.notes[:50]}...")
                if "diabetes" in patient.notes.lower():
                    if "type 2" not in patient.diagnoses:
                        patient.diagnoses.append("Type 2 Diabetes (extracted from notes)")
            return patient
        except Exception as e:
            print(f"Error processing patient data: {e}")
            raise

    def load_medical_knowledge(self, knowledge_source: List[Dict]) -> List[MedicalGuideline]:
        # Simulate loading guidelines from a source (e.g., a CSV, DB, or API)
        guidelines = []
        for item in knowledge_source:
            try:
                guidelines.append(MedicalGuideline(**item))
            except Exception as e:
                print(f"Error loading medical guideline: {e}")
        return guidelines

# --- 3. Knowledge Base & Retrieval Module (Mock) ---
class KnowledgeBase:
    def __init__(self, medical_guidelines: List[MedicalGuideline]):
        self.guidelines = {g.disease.lower(): g for g in medical_guidelines}
        # In a real system, this would be a vector DB with embeddings

    def retrieve_medical_guidelines(self, disease_name: str) -> Optional[MedicalGuideline]:
        print(f"[KnowledgeBase] Retrieving guidelines for: {disease_name}")
        return self.guidelines.get(disease_name.lower())

    def check_drug_interactions(self, medications: List[str]) -> List[str]:
        print(f"[KnowledgeBase] Checking drug interactions for: {', '.join(medications)}")
        # Mock interaction logic
        interactions = []
        if "Metformin" in medications and "Insulin" in medications:
            interactions.append("Potential hypoglycemia risk with Metformin and Insulin. Monitor blood glucose closely.")
        if "Warfarin" in medications and "NSAIDs" in medications:
            interactions.append("Increased bleeding risk with Warfarin and NSAIDs. Avoid co-administration if possible.")
        return interactions

# --- 4. Core LLM Orchestrator (LangGraph Mock) ---
# This section simulates the LangGraph state and node execution logic.
# It does NOT use actual LangChain/LangGraph imports for self-containment.

class GraphState(BaseModel):
    patient_data: PatientData
    current_plan: Optional[TreatmentPlan] = None
    feedback: Optional[str] = None
    plan_history: List[TreatmentPlan] = []
    errors: List[str] = []
    task_list: List[str] = [] # Sub-tasks generated by LLM

class LLMOrchestrator:
    def __init__(self, knowledge_base: KnowledgeBase):
        self.kb = knowledge_base

    def _simulate_llm_response(self, prompt: str, context: Any) -> str:
        # A very basic mock LLM. In reality, this would be a call to OpenAI, Gemini, etc.
        print(f"\n--- MOCK LLM CALL ---\nPrompt: {prompt[:100]}...\nContext: {str(context)[:100]}...\n---------------------")
        if "decompose task" in prompt.lower():
            return f"Sub-tasks for {context['goal']}: 1. Assess current medications. 2. Identify relevant guidelines. 3. Propose initial steps. 4. Check for constraints. 5. Refine plan based on checks. 6. Generate detailed steps." 
        elif "initial assessment" in prompt.lower():
            return f"Patient assessed. Key findings: {context['patient_data'].diagnoses[0]} with current medications {context['patient_data'].medications}."
        elif "generate step" in prompt.lower():
            return f"Generated a step for task: {context['task']}. Description: Review {context['task']} and suggest adjustments. Action: Review and Adjust."
        elif "refine plan" in prompt.lower():
            return f"Plan refined based on feedback: '{context['feedback']}'. Added monitoring steps and dosage adjustments for {context['plan'].steps[0].details.get('medication', 'unknown')}."
        return "Mock LLM response."

    def initial_assessment_node(self, state: GraphState) -> GraphState:
        print("[Orchestrator] Running Initial Assessment Node...")
        patient_data = state.patient_data
        assessment_result = self._simulate_llm_response(
            prompt="Perform an initial assessment of the patient's profile.",
            context={"patient_data": patient_data}
        )
        state.task_list.append("Assessed patient profile.") # Simulate task completion
        print(f"[Orchestrator] Assessment result: {assessment_result}")
        return state

    def plan_decomposition_node(self, state: GraphState) -> GraphState:
        print("[Orchestrator] Running Plan Decomposition Node...")
        goal = f"Develop a personalized treatment plan for {state.patient_data.diagnoses[0]}"
        decomposed_tasks_str = self._simulate_llm_response(
            prompt=f"Decompose task: {goal} into smaller, manageable sub-tasks.",
            context={"goal": goal}
        )
        # A very simple parsing for mock tasks
        state.task_list = [t.strip() for t in decomposed_tasks_str.split("\n")[0].split(":")[1].split(". ") if t.strip()]
        print(f"[Orchestrator] Decomposed tasks: {state.task_list}")
        return state

    def plan_generation_node(self, state: GraphState) -> GraphState:
        print("[Orchestrator] Running Plan Generation Node...")
        if not state.task_list:
            state.errors.append("No tasks to generate plan steps from.")
            return state

        current_task = state.task_list.pop(0) # Take the first task
        print(f"[Orchestrator] Generating step for task: {current_task}")

        # Retrieve relevant guidelines for the primary diagnosis
        primary_diagnosis = state.patient_data.diagnoses[0]
        guideline = self.kb.retrieve_medical_guidelines(primary_diagnosis)

        step_description = f"Based on '{current_task}' and guidelines for {primary_diagnosis}: "
        step_details = {"source_task": current_task}

        if guideline:
            step_description += guideline.recommendations[0] if guideline.recommendations else "No specific recommendation found."
            step_details["guideline_id"] = guideline.guideline_id
            if "medication" in current_task.lower() and guideline.dosage_info:
                medication = list(guideline.dosage_info.keys())[0] # Take first medication from dosage info
                dosage = guideline.dosage_info[medication]
                step_details["medication"] = medication
                step_details["dosage"] = dosage
                step_description += f" Consider {medication} at {dosage}."

        # Simulate LLM generating a detailed step
        llm_step_response = self._simulate_llm_response(
            prompt=f"Generate a detailed treatment plan step for task: {current_task}",
            context={"task": current_task, "guideline": guideline.recommendations[0] if guideline else "None"}
        )
        step_description = llm_step_response.split("Description: ")[1].split(" Action:")[0] # Simple parse
        action_type = llm_step_response.split("Action: ")[1].strip() # Simple parse

        new_step = TreatmentPlanStep(
            step_id=f"step_{len(state.current_plan.steps) + 1 if state.current_plan else 1}",
            description=step_description,
            action_type=action_type,
            details=step_details
        )

        if state.current_plan:
            state.current_plan.steps.append(new_step)
        else:
            state.current_plan = TreatmentPlan(
                plan_id=f"plan_{state.patient_data.patient_id}_{len(state.plan_history) + 1}",
                patient_id=state.patient_data.patient_id,
                goal=f"Personalized plan for {state.patient_data.diagnoses[0]}",
                steps=[new_step]
            )
        return state

    def constraint_checking_node(self, state: GraphState) -> GraphState:
        print("[Orchestrator] Running Constraint Checking Node...")
        if not state.current_plan:
            state.errors.append("Cannot check constraints, no plan exists.")
            return state

        medications_in_plan = [step.details.get("medication") for step in state.current_plan.steps if step.details.get("medication")]
        all_medications = list(set(state.patient_data.medications + medications_in_plan))

        interactions = self.kb.check_drug_interactions(all_medications)

        if interactions:
            error_msg = f"Constraint violations found: {'; '.join(interactions)}"
            state.errors.append(error_msg)
            state.feedback = error_msg # Provide feedback for refinement
            print(f"[Orchestrator] {error_msg}")
        else:
            print("[Orchestrator] No significant drug interactions found.")
            state.feedback = "No major issues found, plan looks good initially."
        return state

    def feedback_loop_node(self, state: GraphState) -> GraphState:
        print("[Orchestrator] Running Feedback Loop Node (Simulated External Feedback)...")
        # In a real system, this would involve human review or a monitoring system providing feedback.
        # For this mock, if there are errors, feedback is negative; otherwise, it's positive.
        if state.errors:
            state.feedback = f"Critique: Some constraints violated: {'; '.join(state.errors)}. Plan needs refinement."
        elif not state.current_plan or not state.current_plan.steps:
            state.feedback = "Critique: Plan is empty or incomplete. Needs more steps."
        elif len(state.current_plan.steps) < 3: # Arbitrary check for completeness
            state.feedback = "Critique: Plan seems too brief. Consider adding more details or monitoring steps."
        else:
            state.feedback = "Positive feedback: Plan looks reasonable, proceed to finalize."

        print(f"[Orchestrator] Simulated feedback: {state.feedback}")
        return state

    def plan_refinement_node(self, state: GraphState) -> GraphState:
        print("[Orchestrator] Running Plan Refinement Node...")
        if state.feedback and state.current_plan:
            refined_response = self._simulate_llm_response(
                prompt=f"Refine the current treatment plan based on the following feedback: {state.feedback}",
                context={"plan": state.current_plan, "feedback": state.feedback}
            )
            # Mock refinement: add a new step or modify existing based on feedback
            if "hypoglycemia risk" in state.feedback.lower() and state.current_plan:
                new_step = TreatmentPlanStep(
                    step_id=f"step_{len(state.current_plan.steps) + 1}",
                    description="Add frequent blood glucose monitoring and patient education on hypoglycemia symptoms.",
                    action_type="monitoring_education",
                    details={"reason": "Hypoglycemia risk from drug interaction"}
                )
                state.current_plan.steps.append(new_step)
                print("[Orchestrator] Added hypoglycemia monitoring step due to feedback.")

            state.current_plan.status = "refined"
            print(f"[Orchestrator] Plan refined: {refined_response}")
            state.errors = [] # Clear errors after refinement attempt
        return state

    def should_continue_planning(self, state: GraphState) -> str:
        # Simple conditional logic for the graph
        if state.task_list:
            return "continue_generating"
        elif state.feedback and ("Critique" in state.feedback or state.errors):
            return "refine_plan"
        else:
            return "end_planning"

    def build_graph(self):
        # Mocking LangGraph for demonstration
        # In a real LangGraph, you'd use Graph().add_node(), add_edge(), etc.

        print("[Orchestrator] Building a mock LangGraph workflow...")

        # Define a simplified sequence based on node functions
        # This represents the flow: Start -> Assess -> Decompose -> (Loop: Generate -> Check) -> Feedback -> Refine -> (Loop: Generate -> Check) / End
        # For a true LangGraph, state management and transitions would be more explicit.

        class MockStateGraph:
            def __init__(self, orchestrator_instance):
                self.orchestrator = orchestrator_instance
                self.nodes = {
                    "initial_assessment": self.orchestrator.initial_assessment_node,
                    "plan_decomposition": self.orchestrator.plan_decomposition_node,
                    "plan_generation": self.orchestrator.plan_generation_node,
                    "constraint_checking": self.orchestrator.constraint_checking_node,
                    "feedback_loop": self.orchestrator.feedback_loop_node,
                    "plan_refinement": self.orchestrator.plan_refinement_node,
                }
                self.current_node = None

            def invoke(self, initial_state: GraphState):
                state = initial_state
                history = []

                # Initial sequence
                state = self.nodes["initial_assessment"](state)
                state = self.nodes["plan_decomposition"](state)

                # Loop for plan generation and checking
                max_gen_iterations = 5 # Prevent infinite loop in mock
                gen_iter = 0
                while gen_iter < max_gen_iterations and state.task_list:
                    print(f"\n--- Generation Iteration {gen_iter + 1} ---")
                    state = self.nodes["plan_generation"](state)
                    state = self.nodes["constraint_checking"](state)

                    # Simulate decision: If errors and tasks remaining, try to refine
                    if state.errors and state.task_list: # If there are errors and more tasks, force a feedback/refine cycle earlier
                        print("[Mock Graph] Errors found during generation, forcing early feedback/refinement.")
                        state = self.nodes["feedback_loop"](state)
                        if "Critique" in state.feedback: # Only refine if feedback is critical
                            state = self.nodes["plan_refinement"](state)
                            state.task_list.append("Re-evaluate and incorporate feedback") # Add a task to ensure plan generation accounts for refinement
                            # If plan was refined, we might want to re-check constraints (loop back)
                            state = self.nodes["constraint_checking"](state) # Re-check after refinement

                    gen_iter += 1

                # Final feedback and potential refinement if not already done
                print("\n--- Final Feedback & Refinement Phase ---")
                state = self.nodes["feedback_loop"](state)
                if "Critique" in state.feedback and (state.errors or len(state.current_plan.steps) < 3): # Force refinement if critical feedback or incomplete
                     state = self.nodes["plan_refinement"](state)

                print("\n--- Graph Execution Finished ---")
                return state

        return MockStateGraph(self)



# --- Main Execution Flow ---
if __name__ == "__main__":
    print("Starting AI-powered Personalized Treatment Plan Generator...")

    # 1. Initialize Data Processor
    data_processor = DataProcessor()

    # Sample Patient Data
    raw_patient_data = {
        "patient_id": "P001",
        "age": 65,
        "gender": "Female",
        "diagnoses": ["Type 2 Diabetes", "Hypertension"],
        "medications": ["Metformin", "Lisinopril", "Aspirin"],
        "allergies": ["Penicillin"],
        "lab_results": {"HbA1c": 8.2, "Blood Pressure": "140/90"},
        "notes": "Patient reports occasional dizziness. History of mild renal impairment. Needs better blood glucose control."
    }

    # Process patient data
    patient = data_processor.process_patient_data(raw_patient_data)
    print(f"\nProcessed Patient Data: {patient.model_dump_json(indent=2)}")

    # Sample Medical Knowledge Base (mock)
    mock_medical_guidelines = [
        {
            "guideline_id": "G001",
            "disease": "Type 2 Diabetes",
            "recommendations": [
                "Intensive lifestyle modification (diet, exercise).",
                "Metformin is first-line pharmacotherapy.",
                "Consider GLP-1 receptor agonists or SGLT2 inhibitors if Metformin monotherapy is insufficient."
            ],
            "contraindications": ["Severe renal impairment for Metformin"],
            "dosage_info": {"Metformin": "500mg BID, titrate up to 2000mg/day"}
        },
        {
            "guideline_id": "G002",
            "disease": "Hypertension",
            "recommendations": [
                "Lifestyle modifications (DASH diet, reduced sodium).",
                "First-line agents include ACE inhibitors, ARBs, Thiazide diuretics, or Calcium Channel Blockers."
            ],
            "contraindications": [],
            "dosage_info": {"Lisinopril": "10-40mg QD"}
        }
    ]

    # 2. Initialize Knowledge Base
    knowledge_base = KnowledgeBase(data_processor.load_medical_knowledge(mock_medical_guidelines))

    # 3. Initialize LLM Orchestrator
    orchestrator = LLMOrchestrator(knowledge_base)

    # 4. Build and Invoke the Mock Graph
    mock_graph = orchestrator.build_graph()

    # Initial state for the graph
    initial_graph_state = GraphState(patient_data=patient)

    final_state = mock_graph.invoke(initial_graph_state)

    print("\n--- Final Generated Treatment Plan ---")
    if final_state.current_plan:
        print(f"Plan ID: {final_state.current_plan.plan_id}")
        print(f"Patient ID: {final_state.current_plan.patient_id}")
        print(f"Goal: {final_state.current_plan.goal}")
        print(f"Status: {final_state.current_plan.status}")
        print("Steps:")
        for step in final_state.current_plan.steps:
            print(f"  - [{step.step_id}] {step.description} (Action: {step.action_type})")
            if step.details:
                print(f"    Details: {step.details}")
    else:
        print("No treatment plan was generated.")

    if final_state.errors:
        print("\n--- Errors/Warnings During Planning ---")
        for error in final_state.errors:
            print(f"- {error}")

