import math

class MathTutorAgent:
    def __init__(self):
        """
        Initializes the MathTutorAgent. In a real application, this might
        initialize an LLM client or other necessary components.
        """
        pass

    def _translate_problem_to_code(self, problem: str) -> str:
        """
        Simulates translating a natural language math problem into executable Python code.
        In a real Program-aided Language Model (PAL) system, this would involve
        a sophisticated LLM generating code based on the problem's context and logic.
        For this demonstration, it uses simple keyword matching.
        """
        print(f"[AGENT] Translating problem to code: '{problem}'")
        problem_lower = problem.lower()

        if "what is 5 + 3" in problem_lower:
            return "result = 5 + 3"
        elif "calculate the square root of 16" in problem_lower:
            return "import math\nresult = math.sqrt(16)"
        elif "x = 10, y = 5, what is x * y?" in problem_lower:
            return "x = 10\ny = 5\nresult = x * y"
        elif "find the area of a rectangle with length 7 and width 4" in problem_lower:
            return "length = 7\nwidth = 4\nresult = length * width"
        else:
            # Fallback for problems not directly matched. A real LLM would be more versatile.
            return f"# Could not directly translate \"{problem}\" to executable code.\nresult = 'Unable to compute directly.'"

    def _execute_code(self, code: str) -> str:
        """
        Executes the provided Python code in a controlled environment and captures its output.
        
        NOTE: Using `exec()` directly can pose security risks in production environments.
        For a robust application, consider a secure sandboxing mechanism (e.g., separate process,
        docker container, or a dedicated code execution service).
        """
        print(f"[AGENT] Executing code:\n---\n{code}\n---")
        local_scope = {}
        try:
            # Execute the code. '__builtins__' is set to None to restrict access to built-in functions
            # For a real application, more granular control over globals/locals is needed.
            exec(code, {"math": math}, local_scope) 
            if 'result' in local_scope:
                return str(local_scope['result'])
            else:
                return "No explicit 'result' variable found after execution." # Ensure code assigns to 'result'
        except Exception as e:
            return f"Error during code execution: {e}"

    def _generate_explanation(self, problem: str, code: str, result: str) -> str:
        """
        Simulates generating a step-by-step explanation for the solution.
        In a real PAL system, an LLM would analyze the problem, the generated code,
        and the execution result to create a coherent and pedagogical explanation.
        """
        print(f"[AGENT] Generating explanation for problem: '{problem}' with result: '{result}'")
        problem_lower = problem.lower()

        if "5 + 3" in problem_lower:
            return f"To solve '{problem}', the agent translated it to `result = 5 + 3`. Executing this code yields {result}. The sum of 5 and 3 is indeed {result}."
        elif "square root of 16" in problem_lower:
            return f"The problem '{problem}' was translated to `import math\nresult = math.sqrt(16)`. The code executed to produce {result}. The square root of 16 is {result}."
        elif "x = 10, y = 5, what is x * y?" in problem_lower:
            return f"For the problem '{problem}', the agent executed `x = 10\ny = 5\nresult = x * y`. The computed result is {result}. Multiplying 10 by 5 gives {result}."
        elif "area of a rectangle with length 7 and width 4" in problem_lower:
            return f"The problem '{problem}' was solved by translating it to `length = 7\nwidth = 4\nresult = length * width`. The area calculated is {result}."
        else:
            return f"The problem was '{problem}'. The code executed was:\n```python\n{code}\n```\nAnd the result obtained was: {result}. A detailed explanation would typically be generated by an advanced AI model analyzing the steps."

    def solve_problem(self, problem: str):
        """
        Orchestrates the entire process of solving a problem:
        1. Translates the natural language problem into executable Python code.
        2. Executes the generated code.
        3. Generates a step-by-step explanation of the solution.
        """
        print(f"\n>>> Initiating solution for problem: '{problem}' <<<")
        
        generated_code = self._translate_problem_to_code(problem)
        execution_result = self._execute_code(generated_code)
        explanation = self._generate_explanation(problem, generated_code, execution_result)

        print("\n--- Final Solution ---")
        print(f"Original Problem: {problem}")
        print(f"Generated Code:\n```python\n{generated_code}\n```")
        print(f"Execution Result: {execution_result}")
        print(f"Explanation: {explanation}")
        print("----------------------\n")
        
        return {
            "problem": problem,
            "generated_code": generated_code,
            "execution_result": execution_result,
            "explanation": explanation
        }

# Example Usage:
if __name__ == "__main__":
    tutor = MathTutorAgent()

    # Example 1: Simple arithmetic
    tutor.solve_problem("What is 5 + 3?")

    # Example 2: Using a built-in math function
    tutor.solve_problem("Calculate the square root of 16.")

    # Example 3: Variable assignment and operation
    tutor.solve_problem("If x = 10 and y = 5, what is x * y?")
    
    # Example 4: A more complex problem for the demo
    tutor.solve_problem("Find the area of a rectangle with length 7 and width 4.")

    # Example 5: A problem not directly handled by the simple translation logic
    tutor.solve_problem("What is the derivative of x^2?")
