import pandas as pd
import streamlit as st
import json

# --- 1. Template Management Module ---
class TemplateManager:
    def __init__(self, templates_data):
        self.templates = templates_data

    def get_template(self, category):
        return self.templates.get(category, self.templates.get("default"))

# --- 2. LLM Integration Module (Mocked) ---
class LLMClient:
    def __init__(self, api_key=None):
        self.api_key = api_key # In a real app, you'd use this for OpenAI API

    def generate_description(self, prompt):
        # This is a mock implementation. In a real application,
        # you would call the OpenAI API here.
        # Example: response = openai.ChatCompletion.create(model="gpt-3.5-turbo", messages=[{"role": "user", "content": prompt}])
        # return response.choices[0].message.content

        # For demonstration, we'll just simulate a generation
        if "{product_name}" in prompt:
            # Simple substitution for demonstration if placeholders are still in prompt
            return prompt.replace("{product_name}", "(Product Name Here)").replace("{category}", "(Category Here)") + " - Generated by LLM (Mock)"
        return prompt + " - Generated by LLM (Mock)"

# --- 3. Generation Orchestration Module ---
class ProductDescriptionGenerator:
    def __init__(self, template_manager, llm_client):
        self.template_manager = template_manager
        self.llm_client = llm_client

    def generate_for_product(self, product_data):
        category = product_data.get("category", "default")
        template = self.template_manager.get_template(category)

        if not template:
            return f"No template found for category: {category}"

        # Fill known placeholders from product data
        filled_template = template
        for key, value in product_data.items():
            filled_template = filled_template.replace(f"{{{key}}}", str(value))
        
        # Construct the prompt for the LLM
        # The LLM's job here is to 'beautify' and complete the description
        # based on the partially filled template and context.
        prompt = f"Elaborate and enhance the following product description snippet, making it engaging and SEO-friendly. Ensure all factual details from the snippet are retained and expand on them naturally:\n\n'{filled_template}'\n\nProduct details for context: {json.dumps(product_data)}"

        generated_text = self.llm_client.generate_description(prompt)
        return generated_text

# --- Streamlit UI --- 
st.set_page_config(layout="wide")
st.title("E-commerce Product Description Generator")

# Default templates
default_templates = {
    "electronics": "Discover the cutting-edge {product_name}, a {brand} innovation designed for {key_features}. Experience {feature_1} and {feature_2} with its sleek {color} finish.",
    "clothing": "Step out in style with our new {product_name}. Crafted from luxurious {material}, this {category} features {key_features} and is available in {color}. Perfect for {occasion}.".replace("{category}", ""), # empty category initially to be filled
    "default": "Introducing the {product_name}. This versatile {category} offers {key_features}. Made with high-quality {material} and available in a stunning {color}."
}

# --- Initialize components ---
template_manager = TemplateManager(default_templates)
llm_client = LLMClient() # In a real app, pass your OpenAI API key here
product_generator = ProductDescriptionGenerator(template_manager, llm_client)

# --- Data Ingestion & Preprocessing --- 
st.header("1. Product Data Input")

example_product_data = [
    {
        "product_name": "Wireless Bluetooth Headphones",
        "category": "electronics",
        "brand": "SoundBlast",
        "key_features": "noise-cancelling, 30-hour battery, ergonomic design",
        "material": "durable plastic, memory foam",
        "color": "black",
        "feature_1": "immersive audio",
        "feature_2": "seamless connectivity"
    },
    {
        "product_name": "Organic Cotton T-Shirt",
        "category": "clothing",
        "brand": "EcoWear",
        "key_features": "breathable fabric, relaxed fit, eco-friendly dyes",
        "material": "100% organic cotton",
        "color": "forest green",
        "occasion": "everyday wear"
    },
    {
        "product_name": "Smart Home Hub",
        "category": "electronics",
        "brand": "ConnectAll",
        "key_features": "voice control, multi-device support, energy monitoring",
        "material": "recycled plastic",
        "color": "white",
        "feature_1": "centralized control",
        "feature_2": "intuitive setup"
    }
]

if 'product_df' not in st.session_state:
    st.session_state.product_df = pd.DataFrame(example_product_data)

uploaded_file = st.file_uploader("Upload a CSV or JSON file with product data", type=["csv", "json"])

if uploaded_file is not None:
    try:
        if uploaded_file.name.endswith('.csv'):
            df = pd.read_csv(uploaded_file)
        else:
            df = pd.read_json(uploaded_file)
        st.session_state.product_df = df
        st.success("Product data loaded successfully!")
    except Exception as e:
        st.error(f"Error loading file: {e}")

st.subheader("Current Product Data")
st.dataframe(st.session_state.product_df)

# --- Generate Descriptions --- 
st.header("2. Generate Descriptions")

if st.button("Generate Descriptions for All Products"):
    if not st.session_state.product_df.empty:
        generated_descriptions = []
        for index, row in st.session_state.product_df.iterrows():
            product_data_dict = row.to_dict()
            description = product_generator.generate_for_product(product_data_dict)
            generated_descriptions.append(description)
        st.session_state.product_df['generated_description'] = generated_descriptions
        st.success("Descriptions generated!")
        st.rerun()
    else:
        st.warning("Please load product data first.")

if 'generated_description' in st.session_state.product_df.columns:
    st.subheader("Generated Product Descriptions")

    # --- Human Validation & Refinement Module ---
    st.header("3. Human Validation & Refinement")
    edited_df = st.data_editor(
        st.session_state.product_df[['product_name', 'category', 'generated_description']],
        column_config={
            "generated_description": st.column_config.TextColumn(
                "Generated Description",
                help="Edit the generated description if needed.",
                width="large",
                max_chars=500
            ),
        },
        hide_index=True,
        num_rows="dynamic",
    )

    if st.button("Save Validated Descriptions"):
        st.session_state.product_df['final_description'] = edited_df['generated_description']
        st.success("Validated descriptions saved!")
        st.dataframe(st.session_state.product_df[['product_name', 'final_description']])

    st.subheader("Template Management (for refinement)")
    st.info("This section is for future expansion to allow users to edit and add templates dynamically. For now, templates are hardcoded.")
    st.json(default_templates)
else:
    st.info("Click 'Generate Descriptions for All Products' to start the process.")
