import torch
from transformers import T5ForConditionalGeneration, T5Tokenizer
from fastapi import FastAPI
from pydantic import BaseModel
import gradio as gr
import requests
import threading
import uvicorn
import time

model_name = "t5-base"
tokenizer = T5Tokenizer.from_pretrained(model_name)
model = T5ForConditionalGeneration.from_pretrained(model_name)

app = FastAPI()

class QueryRequest(BaseModel):
    query: str
    num_paraphrases: int = 3
    max_length: int = 150
    num_beams: int = 5

def paraphrase_and_respond(query: str, num_paraphrases: int, max_length: int, num_beams: int) -> list[str]:
    generated_responses = []

    inputs = tokenizer.encode("answer: " + query, return_tensors="pt", max_length=512, truncation=True)
    outputs = model.generate(inputs, max_length=max_length, num_beams=num_beams, early_stopping=True)
    original_response = tokenizer.decode(outputs[0], skip_special_tokens=True)
    generated_responses.append(f"Original Query Response: {original_response}")

    paraphrase_inputs = tokenizer.encode("paraphrase: " + query, return_tensors="pt", max_length=512, truncation=True)
    paraphrase_outputs = model.generate(
        paraphrase_inputs,
        max_length=max_length,
        num_beams=num_beams + 2,
        num_return_sequences=num_paraphrases,
        early_stopping=True,
        no_repeat_ngram_size=2,
    )

    paraphrased_queries = [tokenizer.decode(g, skip_special_tokens=True) for g in paraphrase_outputs]

    for i, p_query in enumerate(paraphrased_queries):
        if p_query.strip().lower() == query.strip().lower():
            continue
        response_inputs = tokenizer.encode("answer: " + p_query, return_tensors="pt", max_length=512, truncation=True)
        response_outputs = model.generate(response_inputs, max_length=max_length, num_beams=num_beams, early_stopping=True)
        p_response = tokenizer.decode(response_outputs[0], skip_special_tokens=True)
        generated_responses.append(f"Paraphrased ({i+1}): \"{p_query}\" -> Response: {p_response}")

    return generated_responses

@app.post("/generate_suggestions")
async def get_suggestions(request: QueryRequest):
    suggestions = paraphrase_and_respond(
        request.query,
        request.num_paraphrases,
        request.max_length,
        request.num_beams
    )
    return {"suggestions": suggestions}

def gradio_interface_fn(customer_query: str) -> str:
    if not customer_query:
        return "Please enter a customer query."

    fastapi_url = "http://127.0.0.1:8000/generate_suggestions"
    payload = {
        "query": customer_query,
        "num_paraphrases": 3,
        "max_length": 150,
        "num_beams": 5
    }
    headers = {"Content-Type": "application/json"}

    try:
        response = requests.post(fastapi_url, json=payload, headers=headers)
        response.raise_for_status()
        suggestions = response.json().get("suggestions", [])
        return "\n\n".join(suggestions)
    except requests.exceptions.ConnectionError:
        return "Error: Could not connect to the FastAPI backend. Make sure it is running."
    except requests.exceptions.RequestException as e:
        return f"Error from FastAPI backend: {e}"
    except Exception as e:
        return f"An unexpected error occurred: {e}"

gr_interface = gr.Interface(
    fn=gradio_interface_fn,
    inputs=gr.Textbox(lines=5, label="Customer Query", placeholder="Enter customer query here..."),
    outputs=gr.Textbox(lines=10, label="Response Suggestions"),
    title="Customer Support Assistant with Prompt Paraphrasing",
    description="Enter a customer query to get diverse response suggestions generated by an AI model that uses prompt paraphrasing."
)

def run_fastapi():
    uvicorn.run(app, host="127.0.0.1", port=8000, log_level="error")

if __name__ == "__main__":
    fastapi_thread = threading.Thread(target=run_fastapi, daemon=True)
    fastapi_thread.start()

    time.sleep(3)

    print("FastAPI backend is starting on http://127.0.0.1:8000")
    print("Launching Gradio frontend...")
    gr_interface.launch(server_name="0.0.0.0", server_port=7860)